#!/usr/bin/env node
// Writes the Homebrew formula for the danjdewhurst/homebrew-tap repository
// from a release's checksums file, so `brew install danjdewhurst/tap/story-skills`
// installs the standalone `story` binary for macOS or Linux. The publish
// workflow runs it after the binaries are attached to the GitHub release.
//
// Usage:
//   node scripts/homebrew-formula.js <version> <checksums-file> > story-skills.rb
import fs from "node:fs";
import { pathToFileURL } from "node:url";
import { TARGETS, archiveName } from "./build-binaries.js";

export const REPOSITORY = "danjdewhurst/story-skills";

// { "story-skills_1.2.3_darwin_arm64.tar.gz": "<sha256>", ... }
export function parseChecksums(text) {
  const sums = {};
  for (const line of text.split(/\r?\n/)) {
    const match = /^([0-9a-f]{64}) [ *](\S+)$/.exec(line.trim());
    if (match) {
      sums[match[2]] = match[1];
    }
  }
  return sums;
}

export function formula(version, sums) {
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    throw new Error(`version must be X.Y.Z, not ${version}`);
  }
  const block = (os, arch) => {
    const target = TARGETS.find((entry) => entry.os === os && entry.arch === arch);
    const file = archiveName(version, target);
    const sha = sums[file];
    if (!sha) {
      throw new Error(`the checksums file has no entry for ${file}`);
    }
    return [
      `      url "https://github.com/${REPOSITORY}/releases/download/v${version}/${file}"`,
      `      sha256 "${sha}"`
    ].join("\n");
  };
  return `# typed: false
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.js in ${REPOSITORY}. Do not edit:
# the release workflow rewrites it for every release.
class StorySkills < Formula
  desc "Companion CLI for Story Skills: validate, check, and build markdown story projects"
  homepage "https://github.com/${REPOSITORY}"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
${block("darwin", "arm64")}
    end
    if Hardware::CPU.intel?
${block("darwin", "x64")}
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
${block("linux", "arm64")}
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
${block("linux", "x64")}
    end
  end

  def install
    bin.install "story"
  end

  test do
    assert_equal "${version}", shell_output("#{bin}/story --version").strip
  end
end
`;
}

function main() {
  const [version, checksumsFile] = process.argv.slice(2);
  if (!version || !checksumsFile) {
    throw new Error("usage: node scripts/homebrew-formula.js <version> <checksums-file>");
  }
  process.stdout.write(formula(version, parseChecksums(fs.readFileSync(checksumsFile, "utf8"))));
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    main();
  } catch (error) {
    console.error(`homebrew-formula: ${error.message}`);
    process.exit(1);
  }
}

