// Manuscript assembly, export, synopsis, and build formats.
import fs from "node:fs";
import path from "node:path";
import { chapterChronology } from "./chronology.js";
import { entityStateAt } from "./progressions.js";
import { isInsideGitDirectory, isPlanning, lstatIfExists, nearestExistingAncestor, portablePath, projectPath, readFilePrefix, removeDirectory, removeFile, writeFile } from "./files.js";
import { CODEX_GENERATOR, CODEX_KINDS, codexPages } from "./codex.js";
import { PROGRESS_FILE } from "./progress.js";
import {
  chapterHeading,
  chapterProse,
  characterCount,
  extractSection,
  kebabCase,
  scanComments,
  titleCaseSlug,
  trimBlankLines,
  wordCount
} from "./markdown.js";
import { chapterByline, copyrightPage, leadNames, metadataSheet, nameList, publishingMeta } from "./publishing.js";
import { DEFAULT_TRIM, estimateBookPages, indentsFirstLines, printHtml, reviewHtml, TRIM_SIZES } from "./html.js";
import { narrationScript, pronunciationGuide } from "./narration.js";
import { SCENE_SETTINGS, fountainScript } from "./fountain.js";
import { inkSource } from "./ink.js";
import { derivedIfid, isIfid, tweeSource } from "./twee.js";
import { DEFAULT_PAPER, htmlBook, SHUNN_PAPERS, shunnHtml, writeDocx, writeEpub, writeShunnDocx, writeShunnMarkdown } from "./packaging.js";
import { renderPdf, resolvePdfEngine } from "./pdf.js";
import { buildStyle, styleSheetFile, validateBuildStyle } from "./build-style.js";
import { wordSpans } from "./words.js";
import { fillLabel, joinNames } from "./languages/index.js";
import { endsSentence, splitSentences } from "./sentences.js";
import { warn } from "./findings.js";
import { EXIT_CODES, projectError, refusedError, usageError, withDefaultExitCode } from "./exit-codes.js";
import {
  scanProject,
  assertProjectParses,
  parseDecimalInteger,
  isKebabId,
  branchGraph,
  readMarkdown,
  fileStem,
  SOURCE_ROOT_FILES,
  SOURCE_DIRECTORIES,
  asArray,
  coverIsReady,
  coverImage,
  relative
} from "./scan.js";

export function exportManuscript(root, options = {}) {
  const project = scanProject(root);
  const manuscript = manuscriptParts(project, options.generatedBy === undefined ? "export" : "build");
  const output = resolveOutputPath(project, options.out, "dist/manuscript.md", options.enforceRoot);
  const generatedBy = options.generatedBy ?? "story export";
  const lines = [`# ${manuscript.title}`, "", `<!-- Generated by ${generatedBy}. -->`, ""];
  const pushMatter = (entry) => {
    if (entry.heading) {
      lines.push(`# ${entry.title}`, "");
    }
    lines.push(entry.body, "");
  };

  manuscript.front.forEach(pushMatter);
  for (const chapter of manuscript.chapters) {
    lines.push(`# ${chapter.heading}`, "", ...(chapter.byline === "" ? [] : [`*${chapter.byline}*`, ""]), chapter.body, "");
  }
  manuscript.back.forEach(pushMatter);

  writeFile(output.outFile, `${lines.join("\n").trimEnd()}\n`, output.writeOptions);
  return { outFile: output.outFile, chapters: project.chapters.length, warnings: manuscript.warnings };
}

export function buildBook(root, options = {}) {
  const format = normalizeBuildFormat(options.format ?? "markdown");
  if (options.trim !== undefined && format !== "print") {
    throw usageError("--trim applies only to --format print");
  }
  // Like --format, the trim name is case-insensitive (A5, 6X9), and an
  // unknown one fails before the manuscript is assembled.
  const trim = options.trim === undefined ? DEFAULT_TRIM : String(options.trim).trim().toLowerCase();
  if (!TRIM_SIZES.has(trim)) {
    throw usageError(`Unsupported trim size: ${options.trim}. Supported sizes: ${[...TRIM_SIZES.keys()].join(", ")}`);
  }
  // --paper sets the page of the two Shunn builds that have pages: the PDF
  // and the DOCX. A story.md default waits for one of them, as a default
  // --pdf-engine waits for --pdf, so a writer can set A4 once.
  const shunnPages = (format === "shunn" && Boolean(options.pdf)) || (format === "docx" && Boolean(options.shunn));
  const rawPaper = options.paperDefaulted && !shunnPages ? undefined : options.paper;
  if (rawPaper !== undefined && !shunnPages) {
    throw usageError("--paper applies only to --format shunn --pdf and --format docx --shunn (use --trim for --format print)");
  }
  const paper = rawPaper === undefined ? DEFAULT_PAPER : String(rawPaper).trim().toLowerCase();
  if (!SHUNN_PAPERS.has(paper)) {
    throw usageError(`Unsupported paper: ${rawPaper}. Supported papers: ${[...SHUNN_PAPERS.keys()].join(", ")}`);
  }
  if (options.stamp !== undefined && format !== "html") {
    throw usageError("--stamp applies only to --format html");
  }
  // A build label printed in the review copy: one line, no control characters.
  const stamp = options.stamp === undefined ? "" : String(options.stamp).replace(/[\u0000-\u001f\u007f]+/g, " ").trim();
  if (options.stamp !== undefined && stamp === "") {
    throw usageError("--stamp needs a label, such as a date, commit, or round name");
  }
  if (options.noteUrl !== undefined && format !== "html") {
    throw usageError("--note-url applies only to --format html");
  }
  // The note form each paragraph label links to: an http(s) address, so a
  // label can never carry a script.
  const noteUrl = options.noteUrl === undefined ? "" : String(options.noteUrl).replace(/[\u0000-\u0020\u007f]+/g, "");
  if (options.noteUrl !== undefined && !/^https?:\/\/[^/?#]/i.test(noteUrl)) {
    throw usageError("--note-url needs an http or https address, such as a GitHub new-issue link");
  }
  if (options.shunn && format !== "docx") {
    throw usageError("--shunn applies only to --format docx (use --format shunn for a Shunn markdown manuscript)");
  }
  if (options.pdf && format !== "print" && format !== "shunn") {
    throw usageError("--pdf applies only to --format print and --format shunn");
  }
  if (options.pdfEngine !== undefined && !options.pdf) {
    throw usageError("--pdf-engine applies only with --pdf");
  }
  if (options.spoilers && format !== "codex") {
    throw usageError("--spoilers applies only to --format codex");
  }
  const project = scanProject(root);
  if (format === "codex") {
    return buildCodex(project, options.out, Boolean(options.spoilers));
  }
  const extension = options.pdf ? PDF_EXTENSIONS[format] : options.shunn ? SHUNN_DOCX_EXTENSION : BUILD_EXTENSIONS[format];
  const output = resolveOutputPath(project, options.out, `dist/${fileStem(project.storyId)}.${extension}`);

  if (options.pdf) {
    return buildPdf(project, format, { trim, paper }, output, options);
  }

  if (format === "markdown") {
    const result = exportManuscript(project.root, {
      out: output.outFile,
      generatedBy: "story build",
      enforceRoot: output.enforceRoot
    });
    return { ...result, format };
  }

  // The screenplay skeleton reads chapters and scene records, not matter
  // or prose, so a matter problem cannot stop it.
  if (format === "fountain") {
    const screenplay = screenplayOutline(project, bookChapters(project));
    writeFile(output.outFile, fountainScript(screenplay), output.writeOptions);
    return { outFile: output.outFile, chapters: project.chapters.length, format, warnings: screenplay.warnings };
  }

  const manuscript = manuscriptParts(project);
  if (format === "metadata") {
    const book = htmlBook(manuscript);
    const words = manuscript.chapters.reduce((sum, chapter) => sum + wordCount(chapter.body), 0);
    writeFile(output.outFile, metadataSheet({
      title: manuscript.title,
      data: project.story.data,
      meta: manuscript.meta,
      words,
      // A book counted in characters gives its character count.
      ...(manuscript.unit === "characters" ? { characters: manuscript.chapters.reduce((sum, chapter) => sum + characterCount(chapter.body), 0) } : {}),
      pages: { "5.5x8.5": estimateBookPages(book, "5.5x8.5"), "6x9": estimateBookPages(book, "6x9") },
      hasCopyrightPage: manuscript.front.concat(manuscript.back).some((entry) => entry.copyright),
      coverReady: coverIsReady(project),
      pendingPermissions: project.matter.filter((entry) => entry.permission === "pending").map((entry) => entry.id),
      todoChapters: project.chapters.filter((chapter) => chapter.todoMarkers > 0).map((chapter) => chapter.id)
    }), output.writeOptions);
  } else if (format === "twee" || format === "ink") {
    const { branches, ifid } = interactiveStory(project, manuscript, format);
    const passages = branches.passages.map((passage, position) => ({ name: passage.chapter.id, body: manuscript.chapters[position].body, links: passage.links }));
    writeFile(output.outFile, format === "twee"
      ? tweeSource({ title: manuscript.title, ifid, start: passages[0].name, passages })
      : inkSource({ title: manuscript.title, author: manuscript.author, ifid, branching: branches.branching, passages }), output.writeOptions);
    manuscript.warnings.push(...branches.warnings);
  } else if (format === "narration") {
    writeFile(output.outFile, narrationScript(manuscript, pronunciationGuide(project)), output.writeOptions);
  } else if (format === "html" || format === "print") {
    const style = projectBuildStyle(project);
    const book = htmlBook(manuscript, indentsFirstLines(format, style));
    const text = format === "html" ? reviewHtml(book, { stamp, noteUrl, style }) : printHtml(book, trim, style);
    writeFile(output.outFile, text, output.writeOptions);
  } else if (format === "shunn") {
    writeShunnMarkdown(output.outFile, manuscript, shunnMeta(project), output.writeOptions);
  } else if (format === "epub") {
    const cover = project.story.data.cover === undefined ? null : coverImage(project);
    writeEpub(output.outFile, project.storyId, { ...manuscript, cover, style: projectBuildStyle(project) }, output.writeOptions);
  } else if (options.shunn) {
    writeShunnDocx(output.outFile, manuscript, shunnMeta(project), output.writeOptions, paper);
  } else {
    writeDocx(output.outFile, manuscript, output.writeOptions);
  }

  return { outFile: output.outFile, chapters: manuscript.chapters.length, format, warnings: manuscript.warnings };
}

// `--pdf`: the print interior or Shunn manuscript as HTML, rendered by an
// installed engine. The engine is found before the manuscript is assembled,
// so a machine without one fails fast, and the PDF is written like any other
// build, only once the engine has made it.
function buildPdf(project, format, { trim, paper }, output, options) {
  const engine = resolvePdfEngine(options.pdfEngine, { cwd: options.cwd });
  const manuscript = manuscriptParts(project);
  // The Shunn manuscript keeps its fixed format: build-style never reaches it.
  const style = projectBuildStyle(project);
  const html = format === "print" ? printHtml(htmlBook(manuscript, indentsFirstLines(format, style)), trim, style) : shunnHtml(manuscript, shunnMeta(project), paper);
  // A --dry-run finds the engine but does not run it.
  writeFile(output.outFile, isPlanning() ? "" : renderPdf(html, engine), output.writeOptions);
  return { outFile: output.outFile, chapters: manuscript.chapters.length, format, pdf: true, engine: engine.name, warnings: manuscript.warnings };
}

// `build --format codex`: the story bible as linked pages in a folder,
// dist/codex/ by default. A rebuild removes the pages an earlier codex wrote
// there that this one does not, so a removed character's page does not
// linger; a folder that holds anything else is refused rather than mixed
// into.
function buildCodex(project, out, spoilers) {
  assertProjectParses(project, "build");
  // The progress page reads the session log, so an unreadable one stops
  // the build rather than leaving the log off without a word.
  const progressError = project.fileErrors.find((error) => error.file === PROGRESS_FILE);
  if (progressError) {
    throw projectError(`Cannot build the codex: fix this file first (story validate reports it):\n- ${progressError.message}`);
  }
  const output = resolveOutputDirectory(project, out, "dist/codex");
  const pages = codexPages(project, { spoilers });
  // Each page replaces its old copy in one rename, and stale pages go only
  // once every new one is written, so the folder always holds a whole
  // codex and its index.html, even after a failed build.
  const written = new Set();
  for (const page of pages) {
    const file = path.join(output.directory, ...page.path.split("/"));
    writeFile(file, page.html, output.writeOptions);
    written.add(file);
  }
  removeStaleCodexPages(output.directory, written);
  return { outFile: output.directory, chapters: project.chapters.length, format: "codex", pages: pages.length, warnings: [] };
}

// The codex folder: outside the project's source and not holding the
// project, and either new, empty, or an earlier codex.
function resolveOutputDirectory(project, out, defaultRelativePath) {
  const rawOut = out ?? defaultRelativePath;
  if (String(rawOut).trim() === "") {
    throw usageError("--out needs a folder path");
  }
  const directory = path.resolve(project.root, rawOut);
  const enforceRoot = !path.isAbsolute(String(rawOut));
  const toRoot = path.relative(directory, project.root);
  if (!toRoot.startsWith("..") && !path.isAbsolute(toRoot)) {
    throw refusedError(`Refusing to write the codex to ${rawOut}: it holds the project. Use a folder such as dist/codex instead`);
  }
  let stats;
  try {
    assertNotProjectSource(project, directory);
    stats = lstatIfExists(directory);
  } catch (error) {
    throw withDefaultExitCode(error, EXIT_CODES.refused);
  }
  if (stats !== null && !stats.isDirectory()) {
    throw usageError(`--out ${rawOut} is not a folder: give a folder for --format codex`);
  }
  if (stats !== null && fs.readdirSync(directory).length > 0 && !isCodexFolder(directory)) {
    throw refusedError(`Refusing to write the codex into ${projectPath(project.root, directory)}: it holds other files. Use a new or empty folder, such as dist/codex`);
  }
  return { directory, writeOptions: enforceRoot ? { root: project.root } : {} };
}

function isCodexFolder(directory) {
  return isCodexPage(path.join(directory, "index.html"));
}

// The bytes of a page read for the generator tag, which the codex writes
// near the top of <head>. Only these are read, so a page of any size can
// be recognised, and a page that is a symlink or a FIFO is not one the
// codex wrote: it is never followed or read.
const CODEX_HEAD_BYTES = 4096;

function isCodexPage(file) {
  try {
    return readFilePrefix(file, CODEX_HEAD_BYTES).toString("utf8").includes(`<meta name="generator" content="${CODEX_GENERATOR}">`);
  } catch {
    return false;
  }
}

// Removes the pages an earlier codex wrote that this build did not: an
// .html file at the top of the folder or in an entity folder that carries
// the codex generator tag, so a page someone added by hand stays. An
// entity folder left empty goes too.
function removeStaleCodexPages(directory, written) {
  const stalePages = (folder) => fs.readdirSync(folder, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".html"))
    .map((entry) => path.join(folder, entry.name))
    .filter((file) => !written.has(file) && isCodexPage(file));
  for (const folder of [directory, ...CODEX_KINDS.map((kind) => path.join(directory, kind.dir))]) {
    if (lstatIfExists(folder)?.isDirectory() !== true) {
      continue;
    }
    const stale = stalePages(folder);
    stale.forEach((file) => removeFile(file));
    // Counted before the pages go, so a --dry-run, which deletes none, sees
    // the folder the real build would empty.
    if (folder !== directory && fs.readdirSync(folder).length === (isPlanning() ? stale.length : 0)) {
      removeDirectory(folder);
    }
  }
}

// story.md build-style for the EPUB, review copy, and print interior, with
// its extra stylesheet read (`cssText`). A problem stops the build, since a
// style quietly dropped would ship a book that looks wrong.
function projectBuildStyle(project) {
  const errors = [];
  validateBuildStyle(project.story.data, errors, project.root);
  if (errors.length > 0) {
    throw projectError(`Cannot build until story.md build-style is fixed:\n${errors.map((error) => error.message).join("\n")}`);
  }
  const style = buildStyle(project.story.data);
  return { ...style, cssText: style.css === null ? "" : styleSheetFile(project.root, style.css).text };
}

// The chapter graph and IFID behind the twee and ink builds, which refuse
// to build while a choice is malformed or leads nowhere. Chapter ids name
// the passages and knots, so they must be kebab-case.
function interactiveStory(project, manuscript, format) {
  const branches = branchGraph(project);
  const pinned = project.story.data.ifid;
  const node = format === "twee" ? "a passage" : "a knot";
  const problems = [
    ...project.chapters.filter((chapter) => !isKebabId(chapter.id)).map((chapter) => `${relative(project, chapter.file)}: chapter file names must be kebab-case to name ${node}`),
    ...branches.problems.map((problem) => problem.message),
    ...branches.missing.map((choice) => choice.finding.message),
    ...(pinned === undefined || isIfid(pinned) ? [] : ["story.md ifid must be a version 4 UUID, such as 3F2C9A61-7B1D-4E8A-9C3B-2A6D5E4F1B07"])
  ];
  if (problems.length > 0) {
    throw projectError(`Cannot build ${format} until these are fixed:\n${problems.join("\n")}`);
  }
  // A derived IFID changes with the title, and two books with one title
  // share it, so the build says how to pin it.
  const ifid = pinned ?? derivedIfid(project.storyId);
  if (pinned === undefined) {
    manuscript.warnings.push(warn("derived-ifid", `story.md has no ifid, so the build derived ${ifid} from the story id; add ifid: ${ifid} to story.md to keep it if the title changes`, "story.md"));
  }
  return { branches, ifid };
}

// The scene records behind `build --format fountain`, in reading order: each
// book chapter with its scenes by scene number, each scene resolved to its
// location name, setting (the scene's own, else its location's), time (the
// scene's, else its chapter's), and cast (the pov unless only mentioned,
// then characters), by character name. Missing records are warnings, since
// the script still builds with forced headings and notes in their place.
function screenplayOutline(project, book) {
  const warnings = [];
  const locations = new Map(project.locations.map((location) => [location.id, location]));
  const characters = new Map(project.characters.map((character) => [character.id, character]));
  const bookChapters = new Set(project.chapters.map((chapter) => chapter.id));
  const unset = new Set();
  const noScenes = [];
  const chronology = chapterChronology(project);
  for (const scene of project.scenes) {
    if (!bookChapters.has(scene.chapter)) {
      warnings.push(warn("scene-outside-book", `${relative(project, scene.file)} names chapter ${scene.chapter || "(none)"}, which is not in the book, and is left out of the screenplay`, relative(project, scene.file)));
    }
  }
  const chapters = project.chapters.map((chapter, index) => {
    const scenes = project.scenes
      .filter((scene) => scene.chapter === chapter.id)
      .sort((left, right) => left.scene - right.scene || left.file.localeCompare(right.file, "en"))
      .map((scene) => {
        const location = locations.get(scene.location);
        // The location as it stands in this chapter: a progression can
        // rename it or change its setting (a house that burns down).
        const place = location === undefined ? {} : entityStateAt(location.frontmatter, chapter.id, chronology).state;
        const setting = scene.setting || (typeof place.setting === "string" ? place.setting : "");
        const notes = [];
        if (scene.location === "") {
          notes.push("No location on the scene record: set location for the heading.");
          warnings.push(warn("scene-no-location", `${relative(project, scene.file)} has no location; its screenplay heading reads LOCATION TBD`, relative(project, scene.file)));
        } else if (location === undefined) {
          notes.push(`No location record for ${scene.location}: fix the scene's location or add the location.`);
          warnings.push(warn("scene-unknown-location", `${relative(project, scene.file)} names location ${scene.location}, which has no record; run story links`, relative(project, scene.file)));
        }
        if (scene.location !== "" && !SCENE_SETTINGS.has(setting)) {
          notes.push(`No setting: add setting (interior, exterior, or both) to ${location ? `${relative(project, location.file)} or the scene` : "the scene"} for INT. or EXT.`);
          if (location !== undefined) {
            unset.add(scene.location);
          }
        }
        const cast = [];
        for (const id of [scene.mentions.includes(scene.pov) ? "" : scene.pov, ...scene.characters]) {
          const name = id === "" ? "" : String(characters.get(id)?.name ?? titleCaseSlug(id));
          if (name !== "" && !cast.includes(name)) {
            cast.push(name);
          }
        }
        return {
          id: scene.id,
          title: String(scene.title),
          locationName: scene.location === "" ? "" : String(place.name ?? titleCaseSlug(scene.location)),
          setting,
          date: scene.date,
          time: scene.time || chapter.time,
          cast,
          dilemma: scene.dilemma,
          outcome: scene.outcome,
          flashbackTo: scene.flashbackTo,
          notes
        };
      });
    if (scenes.length === 0) {
      noScenes.push(chapter.id);
    }
    return { id: chapter.id, heading: book.chapters[index].heading, scenes };
  });
  if (noScenes.length > 0) {
    warnings.push(warn("chapter-no-scenes", `No scene records for ${noScenes.join(", ")}: the screenplay has no headings for ${noScenes.length === 1 ? "that chapter" : "those chapters"}`));
  }
  if (unset.size > 0) {
    warnings.push(warn("scene-no-setting", `No setting (interior, exterior, or both) for ${[...unset].sort().join(", ")}: their scene headings are forced without INT. or EXT.`));
  }
  return {
    title: project.title,
    authors: book.meta.authors,
    labels: book.meta.labels,
    form: typeof project.story.data.form === "string" ? project.story.data.form : "",
    pack: project.pack,
    chapters,
    warnings
  };
}

// Deterministic synopsis. Budgets are 500 words (1 page) and 1500 (3 pages).
// Level 0 keeps setup (2 sentences), rising action (2), and a Because line
// of climax plus resolution. Level 1 drops rising action. Level 2 also drops
// resolution. The last resort truncates with the same word rules as wordCount.
export function synopsisBook(root, options = {}) {
  const pages = options.pages === undefined ? 1 : parseDecimalInteger(options.pages);
  if (pages !== 1 && pages !== 3) {
    throw usageError(`Unsupported synopsis length: ${options.pages}. Supported pages: 1, 3`);
  }

  const project = scanProject(root);
  assertProjectParses(project, "build a synopsis");
  const budget = pages === 1 ? 500 : 1500;
  const title = project.title;
  const premise = synopsisPremise(project);
  // Three pages carry more of each arc than one, so the longer scaffold has
  // more to work from.
  const detail = pages === 1 ? { setup: 2, rising: 2, climax: 1, resolution: 1 } : { setup: 4, rising: 8, climax: 2, resolution: 2 };

  let text = renderSynopsis(title, premise, project, 0, detail);
  if (wordCount(text) > budget) {
    text = renderSynopsis(title, premise, project, 1, detail);
  }
  if (wordCount(text) > budget) {
    text = renderSynopsis(title, premise, project, 2, detail);
  }
  if (wordCount(text) > budget) {
    text = truncateWords(text, budget);
  }

  const result = { title, logline: premise, pages, budget, words: wordCount(text), sections: synopsisSections(text, project.arcs), text };
  if (options.out === undefined) {
    return result;
  }
  const output = resolveOutputPath(project, options.out, `dist/${fileStem(project.storyId)}.synopsis.md`);
  writeFile(output.outFile, text, output.writeOptions);
  return { ...result, outFile: output.outFile };
}

// The text under each arc's heading in a rendered synopsis, in arc order.
// Each heading is found after the one before it, so an arc name that also
// appears in prose is not mistaken for one; an arc a truncated synopsis
// lost is left out.
function synopsisSections(text, arcs) {
  const found = [];
  let from = 0;
  for (const arc of arcs) {
    const heading = `\n## ${arc.name}\n`;
    const at = text.indexOf(heading, from);
    if (at === -1) {
      break;
    }
    found.push({ arc, start: at + heading.length, headingAt: at });
    from = at + heading.length;
  }
  return found.map((entry, index) => ({
    arc: entry.arc.id,
    name: String(entry.arc.name),
    text: text.slice(entry.start, index + 1 < found.length ? found[index + 1].headingAt : text.length).trim()
  }));
}

// Starter text that init, import, and add arc write. A synopsis must never
// quote it as if it were the story.
const SCAFFOLD_SENTENCES = new Set([
  "Add a 2-3 sentence synopsis here.",
  "Replace with a 2-3 sentence synopsis.",
  "Initial state and inciting pressure.",
  "First escalation.",
  "Second escalation.",
  "Reversal or complication.",
  "Decision point or highest tension.",
  "What changes because of this arc."
]);

function synopsisPremise(project) {
  const sentences = synopsisSentences(extractSection(project.story.body, "Synopsis"), project.pack)
    .filter((sentence) => !/^Imported from .+\.$/.test(sentence));
  return sentences.length > 0 ? sentences[0] : "No logline recorded.";
}

// Sentences of a synopsis section: list markers are dropped and each list
// item ends as a sentence, and scaffold text and HTML comments are skipped.
function synopsisSentences(section, pack) {
  const text = scanComments(String(section), " ").text
    .split(/\r?\n/)
    .map((line) => {
      const item = /^\s*(?:[-*+]|\d+[.)])\s+(.*)$/.exec(line);
      if (!item) {
        return line;
      }
      const content = item[1].trim();
      return endsSentence(content, pack) ? content : `${content}.`;
    })
    .join("\n");
  return splitSentences(text, { capitalStart: false, pack }).filter((sentence) => !SCAFFOLD_SENTENCES.has(sentence));
}

function takeSentences(text, count, pack) {
  return synopsisSentences(text, pack).slice(0, count);
}

// The logline is the first sentence of story.md's ## Synopsis; the skills
// keep the controlling idea in the `premise` field, so the line is labelled
// as the logline.
function renderSynopsis(title, premise, project, level, detail) {
  const lines = [`# Synopsis: ${title}`, "", `Logline: ${premise}`, ""];
  for (const arc of project.arcs) {
    const markdown = readMarkdown(arc.file, project.root);
    lines.push(`## ${arc.name}`, "");
    const setup = takeSentences(extractSection(markdown.body, "Setup"), detail.setup, project.pack);
    if (setup.length > 0) {
      lines.push(setup.join(" "), "");
    }
    if (level === 0) {
      const rising = takeSentences(extractSection(markdown.body, "Rising Action"), detail.rising, project.pack);
      if (rising.length > 0) {
        lines.push(rising.join(" "), "");
      }
    }
    const climax = takeSentences(extractSection(markdown.body, "Climax"), detail.climax, project.pack);
    const resolution = level < 2 ? takeSentences(extractSection(markdown.body, "Resolution"), detail.resolution, project.pack) : [];
    const chain = climax.concat(resolution);
    if (chain.length > 0) {
      lines.push(`Because ${lowercaseCommonStart(chain.join(" "))}`, "");
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

// Sentence openers that are not names, so "Because She chooses" reads
// "Because she chooses"; a name keeps its capital.
const COMMON_OPENERS = new Set([
  "a", "an", "the", "he", "she", "they", "it", "we", "you", "his", "her", "their", "its", "our", "my", "your",
  "this", "that", "these", "those", "when", "after", "before", "once", "in", "at", "on", "with", "without", "by",
  "as", "if", "even", "every", "all", "both", "no", "none", "only", "then", "there", "here", "one", "each"
]);

function lowercaseCommonStart(text) {
  // A whole word only, so "A.J." and "He-Man" keep their capitals.
  const first = /^[A-Za-z]+(?=\s)/.exec(text)?.[0] ?? "";
  return COMMON_OPENERS.has(first.toLowerCase()) ? `${text[0].toLowerCase()}${text.slice(1)}` : text;
}

// The longest start of a token, ending after one of its Chinese, Japanese,
// Thai, Lao, Khmer, or Burmese words, that has at most `room` words; "" if
// none does. Longer starts never have fewer words, so it is a binary search.
function longestFittingPrefix(token, room) {
  const ends = wordSpans(token, /(?!)/gu).map((word) => word.end);
  let low = 0;
  let high = ends.length;
  while (low < high) {
    const middle = Math.ceil((low + high) / 2);
    if (wordCount(token.slice(0, ends[middle - 1])) <= room) {
      low = middle;
    } else {
      high = middle - 1;
    }
  }
  return low === 0 ? "" : token.slice(0, ends[low - 1]);
}

// Cuts the synopsis at the word budget line by line, so headings and
// paragraph breaks survive and only the last paragraph is cut short.
export function truncateWords(text, budget) {
  const kept = [];
  let used = 0;
  for (const line of text.trimEnd().split("\n")) {
    const words = wordCount(line);
    if (used + words <= budget) {
      kept.push(line);
      used += words;
      continue;
    }
    const tokens = [];
    for (const token of line.split(/\s+/).filter((part) => part !== "")) {
      const tokenWords = wordCount(token);
      if (used + tokenWords > budget) {
        // Chinese, Japanese, Thai, Lao, Khmer, and Burmese have no spaces
        // to cut at, so a token in them is cut after its last word that fits.
        const cut = longestFittingPrefix(token, budget - used);
        if (cut !== "") {
          tokens.push(cut);
        }
        break;
      }
      tokens.push(token);
      used += tokenWords;
    }
    if (tokens.length > 0 && !/^#/.test(line)) {
      kept.push(tokens.join(" "));
    }
    break;
  }
  // Never end on a blank line or a heading with nothing under it. A loop
  // rather than a trailing-lines regex, which backtracks exponentially on
  // runs of lines like "#\t".
  while (kept.length > 1 && /^(?:#|[ \t]*$)/.test(kept[kept.length - 1])) {
    kept.pop();
  }
  return `${kept.join("\n")}…\n`;
}

function shunnMeta(project) {
  const data = project.story.data;
  const meta = publishingMeta(data);
  return {
    title: project.title,
    // Like every other build, `authors` wins over `author`, so a co-written
    // book gets a full byline. An anthology with no author of its own heads
    // its pages with the editor's name and credits them on the title page.
    author: joinNames(meta.authors, meta.labels),
    lead: leadNames(meta),
    editors: meta.editors.length === 0 ? "" : fillLabel(meta.labels, "edited-by", { names: joinNames(meta.editors, meta.labels) }),
    labels: meta.labels,
    contact: asArray(data.contact),
    words: project.chapters.reduce((sum, chapter) => sum + chapter.wordCount, 0),
    pack: project.pack,
    // A book counted in characters gives its length in characters.
    ...(project.unit.name === "characters" ? { characters: project.chapters.reduce((sum, chapter) => sum + chapter.count, 0) } : {}),
    // Short fiction runs as one text with `#` between sections rather than
    // as chapters on new pages.
    shortForm: data.form === "short-story" || data.form === "flash"
  };
}

// The book's chapters in order, with their headings and prose, and the
// publishing metadata: the part of the manuscript every build shares,
// including the screenplay skeleton, which reads no matter.
export function bookChapters(project, action = "build") {
  assertProjectParses(project, action);
  if (project.chapters.length === 0) {
    throw projectError("No chapters found to export");
  }

  for (const chapter of project.chapters) {
    if (!chapter.numberValid || chapter.number <= 0) {
      throw projectError(`${relative(project, chapter.file)}: chapter number must be a positive integer to build`);
    }
  }

  const seenNumbers = new Set();
  for (const chapter of project.chapters) {
    if (seenNumbers.has(chapter.number)) {
      throw projectError(`Duplicate chapter number ${chapter.number}: refusing to build with colliding EPUB ids`);
    }
    seenNumbers.add(chapter.number);
  }

  const meta = publishingMeta(project.story.data);
  const chapters = [];
  const warnings = [];
  // An unnumbered chapter (a Prologue, `numbered: false`) prints its title
  // alone and takes no number, so the chapters after it keep the author's
  // numbering: Prologue, Chapter 1, Chapter 2.
  let unnumberedSoFar = 0;
  const keys = new Set();
  for (const chapter of project.chapters) {
    const markdown = readMarkdown(chapter.file, project.root);
    // Only a real title reaches the book: a missing or blank one leaves the
    // heading as plain "Chapter 2", not "Chapter 2: Chapter 02".
    const rawTitle = markdown.data.title;
    const title = rawTitle === undefined || rawTitle === null ? "" : String(rawTitle).trim();
    const numbered = markdown.data.numbered !== false;
    if (!numbered && title === "") {
      throw projectError(`${relative(project, chapter.file)}: an unnumbered chapter needs a title to build`);
    }
    unnumberedSoFar += numbered ? 0 : 1;
    const displayNumber = numbered ? chapter.number - unnumberedSoFar : null;
    // A story's own author in a collection or anthology: printed under the
    // heading, kept out of the prose, so it never counts toward its length.
    const authors = nameList(markdown.data.author);
    const entry = {
      number: chapter.number,
      title,
      authors,
      byline: chapterByline(authors, meta.labels),
      numbered,
      displayNumber,
      heading: numbered ? chapterHeading(displayNumber, title, meta.labels, meta.chapterNumerals) : title,
      // LF only, so a CRLF checkout builds the same bytes as an LF one. The
      // first paragraph keeps a typed indent (see trimBlankLines).
      body: trimBlankLines(chapterProse(markdown.body).replace(/\r\n?/g, "\n"))
    };
    chapters.push({ ...entry, key: chapterKey(entry, keys) });
    if (wordCount(entry.body) === 0) {
      warnings.push(warn("empty-chapter", `${relative(project, chapter.file)} has no prose yet and is built as a heading-only page`, relative(project, chapter.file)));
    }
  }
  return { meta, chapters, warnings };
}

export function manuscriptParts(project, action = "build") {
  const { meta, chapters, warnings } = bookChapters(project, action);

  // Matter ids become EPUB manifest ids and file names, so they must be safe.
  for (const entry of project.matter) {
    if (!isKebabId(entry.id)) {
      throw projectError(`${relative(project, entry.file)}: matter file names must be kebab-case to build`);
    }
  }
  // Unwritten matter (a scaffold with only its heading) stays out of the book.
  const matter = (placement) => project.matter
    .filter((entry) => entry.placement === placement && !entry.empty)
    .map((entry) => ({
      id: entry.id,
      title: entry.title,
      heading: entry.heading,
      copyright: isCopyrightMatter(entry),
      body: trimBlankLines(chapterProse(readMarkdown(entry.file, project.root).body).replace(/\r\n?/g, "\n"))
    }));

  const front = matter("front");
  // A copyright line in story.md becomes the copyright page unless a matter
  // page already provides one.
  const back = matter("back");
  const hasCopyrightPage = [...front, ...back].some((entry) => entry.copyright);
  if (meta.copyright !== "" && !hasCopyrightPage) {
    front.unshift({ id: "copyright", title: fillLabel(meta.labels, "copyright"), heading: false, copyright: true, body: copyrightPage(meta) });
  }

  return {
    title: project.title,
    author: joinNames(meta.authors, meta.labels),
    meta,
    // The count unit, for the print page estimate and narration runtime.
    unit: project.unit.name,
    front,
    chapters,
    back,
    warnings
  };
}

// The review copy's paragraph-label prefix: ch03 for Chapter 3, or the
// title's slug (prologue) for an unnumbered chapter. A slug that is blank,
// looks like another label, or repeats one takes the file number instead.
// The slug is not transliterated, so labels readers have quoted from an
// earlier review copy stay the same.
function chapterKey(chapter, keys) {
  if (chapter.numbered) {
    return `ch${String(chapter.displayNumber).padStart(2, "0")}`;
  }
  let key = kebabCase(chapter.title, { transliterate: false });
  if (key === "" || keys.has(key) || /^(?:ch\d+$|front-|back-|matter-|unnumbered-)/.test(key)) {
    key = `unnumbered-${String(chapter.number).padStart(2, "0")}`;
  }
  keys.add(key);
  return key;
}

// A copyright page is found by its id or its title, once, and every build
// format reads the flag.
function isCopyrightMatter(entry) {
  return entry.id === "copyright" || /copyright/i.test(entry.title);
}

// Skill-owned folders: generated drafts start here (a synopsis in
// submission/, a narration script in adaptations/), but the files are then
// edited by hand, and reader notes exist nowhere else, so --out may add a
// file but never replace one.
const HAND_EDITED_DIRECTORIES = ["feedback", "submission", "publishing", "adaptations"];

function assertNotProjectSource(project, outFile) {
  if (isInsideGitDirectory(outFile, project.root)) {
    throw refusedError(`Refusing to write generated output to ${projectPath(project.root, outFile)}: it is inside a .git folder. Choose a path outside .git`);
  }
  // Check the path as typed and the real path behind any symlinked folder
  // (`lnk -> chapters`), case-insensitively for case-insensitive disks,
  // where `/users/me/book` can name the project at `/Users/me/Book`.
  const realRoot = fs.realpathSync.native(project.root);
  const realTarget = realPathThroughAncestors(outFile);
  const candidates = [[project.root, outFile], [realRoot, realTarget], [realRoot.toLowerCase(), realTarget.toLowerCase()]];
  for (const [root, target] of candidates) {
    const relativePath = path.relative(root, target);
    if (relativePath === "" || relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
      continue;
    }
    const lower = portablePath(relativePath).toLowerCase();
    const [first] = lower.split("/");
    if (SOURCE_ROOT_FILES.has(lower) || SOURCE_DIRECTORIES.includes(first)) {
      throw refusedError(`Refusing to write generated output to ${projectPath(project.root, outFile)}: it is project source. Use a path such as dist/ instead`);
    }
    if (HAND_EDITED_DIRECTORIES.includes(first) && lower.includes("/") && lstatIfExists(outFile) !== null) {
      throw refusedError(`Refusing to overwrite ${projectPath(project.root, outFile)}: files in ${HAND_EDITED_DIRECTORIES.map((dir) => `${dir}/`).join(", ")} may hold hand-written work. Delete it first to regenerate it, or use a path such as dist/ instead`);
    }
  }
}

// The real path of the nearest existing ancestor, with the missing tail
// appended, so a new file under a symlinked folder resolves to its target.
// The walk stops at the latest at the filesystem root, which always exists.
function realPathThroughAncestors(target) {
  const { ancestor, missing } = nearestExistingAncestor(target, fs.existsSync);
  return path.join(fs.realpathSync.native(ancestor), ...missing);
}

export function resolveOutputPath(project, out, defaultRelativePath, enforceRoot) {
  const rawOut = out ?? defaultRelativePath;
  if (String(rawOut).trim() === "") {
    throw usageError("--out needs a file path");
  }
  const outFile = path.resolve(project.root, rawOut);
  const shouldEnforceRoot = enforceRoot ?? !path.isAbsolute(String(rawOut));
  let stats;
  try {
    assertNotProjectSource(project, outFile);
    stats = lstatIfExists(outFile);
  } catch (error) {
    // A target that cannot be checked (a path through a file) is a write
    // that cannot happen.
    throw withDefaultExitCode(error, EXIT_CODES.refused);
  }
  // path.resolve drops a trailing slash, so `--out newdir/` is caught here
  // rather than writing a file named newdir.
  // `dist` is the build folder even before it exists; a stray file there is
  // named as such rather than called a directory.
  const isDist = outFile === path.join(project.root, "dist");
  if (stats?.isDirectory() || /[\\/]$/.test(String(rawOut)) || (isDist && !stats)) {
    throw usageError(`--out ${rawOut} is a directory: give a file path`);
  }
  if (isDist) {
    throw usageError(`--out ${rawOut} is reserved for the build folder: give a file path such as dist/book.md`);
  }
  return {
    outFile,
    enforceRoot: shouldEnforceRoot,
    writeOptions: shouldEnforceRoot ? { root: project.root } : {}
  };
}

// The file extension of each build format; its keys are the formats
// --format accepts, besides BUILD_FORMAT_ALIASES.
export const BUILD_EXTENSIONS = {
  markdown: "md",
  epub: "epub",
  docx: "docx",
  shunn: "shunn.md",
  html: "html",
  print: "print.html",
  narration: "narration.md",
  metadata: "metadata.md",
  fountain: "fountain",
  twee: "twee",
  ink: "ink",
  // A folder of pages, dist/codex/, rather than one file.
  codex: ""
};

// The file extension of a --format docx --shunn build, so it does not
// replace the plain DOCX build in dist/.
export const SHUNN_DOCX_EXTENSION = "shunn.docx";

// The file extension of each format --pdf renders.
export const PDF_EXTENSIONS = { print: "pdf", shunn: "shunn.pdf" };

// Other names --format accepts for a format.
export const BUILD_FORMAT_ALIASES = { md: "markdown" };

function normalizeBuildFormat(value) {
  const format = String(value).trim().toLowerCase();
  if (Object.prototype.hasOwnProperty.call(BUILD_FORMAT_ALIASES, format)) {
    return BUILD_FORMAT_ALIASES[format];
  }

  if (Object.prototype.hasOwnProperty.call(BUILD_EXTENSIONS, format)) {
    return format;
  }

  throw usageError(`Unsupported build format: ${value === "" ? "(empty)" : value}. Supported formats: ${Object.keys(BUILD_EXTENSIONS).join(", ")}`);
}
