import fs from "node:fs";
import path from "node:path";
import { parseFrontmatter, stringifyFrontmatter } from "./frontmatter.js";
import { chapterHeading, fencedLineIndexes, scanComments, splitFences, titleCaseSlug, wordCount } from "./markdown.js";
import { assertProjectParses, createStoryProject, reindexProject, scanProject, writeFile } from "./story.js";

// A lone "I" before a word is the pronoun ("Chapter I Am Legend"), not a numeral.
const ROMAN_NUMERAL = "(?!i\\s+\\S)(?=[ivxlc])c{0,3}(?:xc|xl|l?x{0,3})(?:ix|iv|v?i{0,3})";
const UNIT_WORDS = "one|two|three|four|five|six|seven|eight|nine";
const TENS_WORDS = "twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety";
// Spelled-out chapter numbers below one hundred ("Chapter Twenty-One").
const BELOW_HUNDRED = `(?:(?:${TENS_WORDS})(?:[-\\s](?:${UNIT_WORDS}))?|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|${UNIT_WORDS})`;
// Hundreds come first, so "One Hundred" is not read as "One" and a title.
const WORD_NUMERAL = `(?:(?:${UNIT_WORDS})[-\\s]hundred(?:(?:[-\\s]and)?[-\\s]${BELOW_HUNDRED})?|${BELOW_HUNDRED})`;
// An arabic number may carry a decimal part ("Chapter 12.5").
const CHAPTER_NUMBER = `(?:\\d+(?:\\.\\d+)?|${WORD_NUMERAL}|${ROMAN_NUMERAL})(?=[\\s:.\\-–—]|$)`;
const CHAPTER_HEADING_PATTERN = new RegExp(`^chapter(?![A-Za-z])\\s*(?:${CHAPTER_NUMBER})?\\s*[:.\\-–—]*\\s*(.*)$`, "i");
// A plain-text chapter line ("Chapter 3", "CHAPTER ONE: Arrival") must carry
// a number and nothing else, or a separator before its title, so a sentence
// such as "Chapter 12 was the worst." never splits.
const PLAIN_CHAPTER_PATTERN = new RegExp(`^chapter\\s+${CHAPTER_NUMBER}\\s*(?:[:.\\-–—]+\\s*(.*))?$`, "i");
// Sections that are chapters in their own right but carry no number.
const SECTION_HEADING_PATTERN = /^(?:prologue|epilogue|interlude|afterword)(?![A-Za-z])/i;
// As a plain line, the section name stands alone or before a separator.
const PLAIN_SECTION_PATTERN = /^(?:prologue|epilogue|interlude|afterword)\s*(?:[:.\-–—]+.*)?$/i;
const PLAIN_LINE_MAX_LENGTH = 80;
// A part heading groups chapters; it is prose, never a chapter or the title.
const PART_HEADING = /^part(?![A-Za-z])/i;
// The comment story export and story build write under the book title.
const GENERATED_MARKER = /<!--\s*Generated by story (?:export|build)\.\s*-->/g;
const FRONTMATTER_BLOCK_PATTERN = /^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*(?:\r?\n|$)/;
// A YAML line: blank, a comment, a list item, an indented continuation, or a
// key with no spaces in it ("She said: go now." is prose, not a key).
const YAML_LINE_PATTERN = /^(?:\s*$|\s*#|\s*-\s|\s*-$|\s+\S|(?:[A-Za-z0-9_][A-Za-z0-9_.-]*|"[^"\n]*"|'[^'\n]*')[ \t]*:(?:\s|$))/;
const FRONT_MATTER_NAMES = /^(?:prologue|preface|foreword|introduction|prelude)\b/i;
const CANDIDATE_THRESHOLD = 3;
const CANDIDATE_LIMIT = 25;
const CANDIDATE_STOPWORDS = new Set([
  "A", "An", "And", "At", "But", "By", "Dr", "For", "He", "Her", "His", "I", "If", "In", "It", "Its",
  "Mr", "Mrs", "Ms", "No", "Not", "Of", "On", "Or", "She", "That", "The", "Then", "They", "Their",
  "This", "To", "We", "When", "While", "With", "Yes", "You",
  // Days and months are capitalised but are not names.
  "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
  "January", "February", "March", "April", "May", "June", "July", "August", "September", "October",
  "November", "December"
]);

const MAX_IMPORT_FILE_BYTES = 5 * 1024 * 1024;
const MAX_IMPORT_FILES = 500;

function rejectSymlinkedSource(filePath) {
  if (fs.lstatSync(filePath).isSymbolicLink()) {
    throw new Error('Refusing to import symlinked source: ' + filePath);
  }
}

function assertImportFileSize(filePath) {
  const size = fs.statSync(filePath).size;
  if (size > MAX_IMPORT_FILE_BYTES) {
    throw new Error('Refusing to import oversized file ' + filePath + ': ' + size + ' bytes exceeds the ' + MAX_IMPORT_FILE_BYTES + ' byte limit');
  }
}

export function importManuscript(options) {
  const rawSource = String(options.source ?? "").trim();
  if (!rawSource) {
    throw new Error("An import source file or directory is required");
  }

  const cwd = options.cwd ?? process.cwd();
  const source = path.resolve(cwd, rawSource);
  if (!fs.existsSync(source)) {
    throw new Error(`Import source not found: ${source}`);
  }
  // A story project's bible is not manuscript prose; importing it would turn
  // story.md and the style sheet into chapters.
  if (fs.statSync(source).isDirectory() && fs.existsSync(path.join(source, "story.md"))) {
    throw new Error(`${rawSource} is already a story project (it has story.md); import reads manuscript files, so point it at the draft instead`);
  }

  const warnings = [];
  const chapters = splitChapters(readSourceDocuments(source), warnings);
  if (chapters.length === 0) {
    throw new Error("No chapter content found in import source");
  }

  const created = createStoryProject({
    title: options.title,
    cwd,
    dir: options.dir,
    genre: options.genre,
    subGenre: options.subGenre,
    settingEra: options.settingEra,
    themes: options.themes,
    pov: options.pov,
    tense: options.tense,
    synopsis: options.synopsis,
    defaultSynopsis: `Imported from ${path.basename(source)}. Replace with a 2-3 sentence synopsis.`,
    force: options.force,
    // Check an existing project parses before deleting its chapters, as the
    // other mutating commands do. The chapter files about to be replaced may
    // be broken.
    beforeWrite(root, hasStory) {
      if (!hasStory) {
        return;
      }
      let project;
      try {
        project = scanProject(root);
      } catch {
        // An unsafe layout (a symlinked folder, say) is refused by the
        // starter-file checks that follow, with their own message.
        return;
      }
      assertProjectParses(project, "import", (error) => /^chapters[\\/]chapter-\d+\.md:/i.test(error));
    }
  });

  const chaptersDir = path.join(created.root, "chapters");
  for (const name of fs.readdirSync(chaptersDir)) {
    if (!/^chapter-\d+\.md$/i.test(name)) {
      continue;
    }
    fs.unlinkSync(path.join(chaptersDir, name));
  }

  let totalWords = 0;
  chapters.forEach((chapter, index) => {
    const number = index + 1;
    // Count as the scanner does, without HTML comments.
    const words = wordCount(scanComments(chapter.prose).text);
    totalWords += words;
    const file = path.join(chaptersDir, `chapter-${String(number).padStart(2, "0")}.md`);
    // An untitled numbered heading ("# Chapter 1") takes its new number.
    const title = chapter.title || `Chapter ${number}`;
    writeFile(file, chapterMarkdown(title, number, words, chapter.prose, chapter.unnumbered), { root: created.root });
  });

  reindexProject(created.root);

  return {
    root: created.root,
    storyId: created.storyId,
    keptStory: created.keptStory,
    ignoredOptions: created.ignoredOptions,
    chapters: chapters.length,
    words: totalWords,
    warnings,
    gitignore: created.gitignore,
    candidates: extractNameCandidates(chapters.map((chapter) => chapter.prose).join("\n\n"))
  };
}

// A capitalised name word in any script: "Élodie", "O’Brien", "McAllister",
// "Anna-Maria", "King’s". Curly and straight apostrophes both count.
const NAME_WORD = "(?:(?:Ma?c|[OD]['’])(?=\\p{Lu}))?\\p{Lu}\\p{Ll}+(?:['’]\\p{Ll}+)?(?:-\\p{Lu}\\p{Ll}+)*";
const NAME_RUN_PATTERN = new RegExp(`(?<![\\p{L}\\p{N}'’-])${NAME_WORD}(?:\\s+${NAME_WORD})+(?![\\p{L}\\p{N}])`, "gu");
// A single name word, not part of a run of capitalised words.
const NAME_SINGLE_PATTERN = new RegExp(`(?<![\\p{L}\\p{N}'’-])(?<!${NAME_WORD}\\s+)${NAME_WORD}(?![\\p{L}\\p{N}])(?!\\s+${NAME_WORD})`, "gu");
// After a lowercase word, mid-sentence, a capitalised word is a name.
const MID_SENTENCE = /\p{Ll}[,;:]?\s$/u;
// A word with a capital inside (McAllister, O’Brien, Anna-Maria) is a name
// even where a sentence starts.
const DISTINCTIVE_NAME = /^\p{Lu}.*\p{Lu}/u;

export function extractNameCandidates(prose) {
  const counts = new Map();

  for (const match of prose.matchAll(NAME_RUN_PATTERN)) {
    const words = match[0].replace(/\s+/g, " ").split(" ");
    while (words.length > 0 && CANDIDATE_STOPWORDS.has(words[0])) {
      words.shift();
    }
    if (words.length > 0) {
      addCandidate(counts, withoutPossessive(words.join(" ")));
    }
  }

  for (const match of prose.matchAll(NAME_SINGLE_PATTERN)) {
    const name = withoutPossessive(match[0]);
    if (CANDIDATE_STOPWORDS.has(name)) {
      continue;
    }
    if (DISTINCTIVE_NAME.test(name) || MID_SENTENCE.test(prose.slice(Math.max(0, match.index - 3), match.index))) {
      addCandidate(counts, name);
    }
  }

  return [...counts.entries()]
    .filter(([, count]) => count >= CANDIDATE_THRESHOLD)
    .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0], "en"))
    .slice(0, CANDIDATE_LIMIT)
    .map(([name, count]) => ({ name, count }));
}

// "Élodie’s" counts as "Élodie"; "King’s Road" keeps its inner possessive.
function withoutPossessive(name) {
  return name.replace(/['’]s$/, "");
}

function addCandidate(counts, name) {
  counts.set(name, (counts.get(name) ?? 0) + 1);
}

// Reads a source file as UTF-8 text without its byte-order mark. A zip
// (such as .docx), a binary file, or text in another encoding is refused, so
// no character is silently replaced.
function readSourceText(filePath) {
  const bytes = fs.readFileSync(filePath);
  if (bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b && bytes[2] === 0x03 && bytes[3] === 0x04) {
    throw new Error(`Cannot import ${filePath}: it is a zip archive (such as a .docx or .odt file). Save or export it as markdown or plain text first`);
  }
  if (bytes.includes(0)) {
    throw new Error(`Cannot import ${filePath}: it is a binary or UTF-16 file, not UTF-8 text. Save it as UTF-8 plain text or markdown first`);
  }
  let text;
  try {
    text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    throw new Error(`Cannot import ${filePath}: it is not valid UTF-8 text. Save it as UTF-8 plain text or markdown first`);
  }
  return text.replace(/^\uFEFF/, "");
}

function readSourceDocuments(source) {
  rejectSymlinkedSource(source);
  if (fs.statSync(source).isFile()) {
    assertImportFileSize(source);
    return [{ name: path.basename(source), text: readSourceText(source) }];
  }

  const names = [];
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const fullPath = path.join(source, entry.name);
    if (fs.lstatSync(fullPath).isSymbolicLink()) {
      // Never follow symlinks during import. A symlink that resolves to an
      // importable document is rejected loudly; anything else (subdirectory
      // links, dangling links) is skipped so stray links cannot block a
      // safe import.
      let targetIsDocument = false;
      try {
        targetIsDocument = fs.statSync(fullPath).isFile();
      } catch {
        targetIsDocument = false;
      }
      if (targetIsDocument && /\.(md|markdown|txt)$/i.test(entry.name)) {
        rejectSymlinkedSource(fullPath);
      }
      continue;
    }
    // Hidden files, macOS AppleDouble files (._name), and Word lock files
    // (~$name) are copies or droppings, not chapters.
    if (entry.isFile() && /\.(md|markdown|txt)$/i.test(entry.name) && !/^(?:\.|~\$)/.test(entry.name)) {
      names.push(entry.name);
    }
  }
  names.sort(compareImportNames);
  if (names.length > MAX_IMPORT_FILES) {
    throw new Error('Too many import files in ' + source + ': ' + names.length + ' exceeds the ' + MAX_IMPORT_FILES + ' file limit');
  }
  const documents = names.map((name) => {
    const fullPath = path.join(source, name);
    assertImportFileSize(fullPath);
    return { name, text: readSourceText(fullPath) };
  });

  if (documents.length === 0) {
    throw new Error(`No markdown or text files found in ${source}`);
  }

  return documents;
}

// Numbered files sort numerically. Unnumbered files sort after them, except
// front matter such as a prologue, which sorts first.
function importNameRank(name, nums) {
  if (nums.length > 0) {
    return 1;
  }
  return FRONT_MATTER_NAMES.test(name) ? 0 : 2;
}

export function compareImportNames(left, right) {
  const leftNums = [...left.matchAll(/\d+/g)].map((match) => Number(match[0]));
  const rightNums = [...right.matchAll(/\d+/g)].map((match) => Number(match[0]));
  const rankDiff = importNameRank(left, leftNums) - importNameRank(right, rightNums);
  if (rankDiff !== 0) {
    return rankDiff;
  }
  const length = Math.max(leftNums.length, rightNums.length);
  for (let index = 0; index < length; index += 1) {
    const leftNum = leftNums[index];
    const rightNum = rightNums[index];
    if (leftNum === undefined) {
      return -1;
    }
    if (rightNum === undefined) {
      return 1;
    }
    if (leftNum !== rightNum) {
      return leftNum - rightNum;
    }
  }
  if (left === right) {
    return 0;
  }
  return left < right ? -1 : 1;
}

// Removes leading YAML frontmatter, including YAML the strict parser rejects,
// such as nested maps from Pandoc or Obsidian. A leading `---` scene break is
// kept: a block that opens with a blank line, or has a line that is not YAML
// (a key with spaces, a sentence), is prose.
function withoutLeadingFrontmatter(text) {
  const match = FRONTMATTER_BLOCK_PATTERN.exec(text);
  if (!match) {
    return text;
  }
  const lines = match[1].split(/\r?\n/);
  if (lines[0].trim() === "" || !lines.every((line) => YAML_LINE_PATTERN.test(line))) {
    return text;
  }
  return text.slice(match[0].length);
}

function splitChapters(documents, warnings = []) {
  const chapters = [];

  for (const document of documents) {
    // A bare CR (classic Mac OS) ends a line too.
    const source = document.text.replace(/\r\n?/g, "\n");
    const own = storySkillsChapter(source);
    if (own) {
      chapters.push(own);
      continue;
    }
    const body = withoutLeadingFrontmatter(source);
    // Line numbers in warnings count from the top of the file, frontmatter
    // included.
    const offset = source.slice(0, source.length - body.length).split("\n").length - 1;
    const text = normalizeSource(body, document.name);
    const { sections, unused, markdown } = splitByChapterHeadings(text);
    if (unused.length > 0) {
      const count = unused.length === 1 ? "1 plain-text chapter line was" : `${unused.length} plain-text chapter lines were`;
      const why = markdown
        ? "the file has markdown chapter headings, which take precedence, so make these headings too (## Chapter 1)"
        : "a chapter line splits only when it stands alone between blank lines, so add a blank line after each";
      warnings.push(`${document.name}: ${count} not used to split chapters (first "${unused[0].text}" at line ${unused[0].index + 1 + offset}): ${why}. See "How chapters are split" in docs/manuscripts.md`);
    }
    if (sections.length > 0) {
      chapters.push(...sections);
    } else {
      chapters.push(singleChapter(text, document.name));
    }
  }

  return chapters.filter((chapter) => chapter.prose !== "");
}

// A chapter file in Story Skills' own layout, copied from another project,
// keeps its title and `numbered: false`, and its prose is the text under `## Chapter Text` (the
// outline above it is not book text).
function storySkillsChapter(text) {
  const heading = /^## Chapter Text[ \t]*$/m.exec(text);
  if (!heading) {
    return null;
  }
  let data;
  try {
    data = parseFrontmatter(text).data;
  } catch {
    return null;
  }
  const title = typeof data.title === "string" || typeof data.title === "number" ? String(data.title).trim() : "";
  return { title, prose: text.slice(heading.index + heading[0].length).trim(), unnumbered: data.numbered === false };
}

// Markdown from Pandoc spells an em dash `---` and an en dash `--`, so a
// markdown source gets real dashes (outside code). Plain text has no markdown
// indentation, so leading tabs and spaces (a Scrivener paragraph indent) are
// dropped rather than turning paragraphs into code blocks.
function normalizeSource(text, name) {
  if (/\.te?xt$/i.test(name)) {
    return text.replace(/^[ \t]+/gm, "");
  }
  // Code, HTML comments, link targets and URLs, table separator rows,
  // indented code, and lines of only dashes (scene breaks) keep their hyphens.
  return splitFences(text).map((part) => (part.fenced ? part.text : protectComments(part.text, (prose) => {
    // An indented line is code, unless it continues a list item.
    let inList = false;
    return prose.split("\n").map((line) => {
      const indented = /^(?: {4}|\t)/.test(line);
      if (!indented && line.trim() !== "") {
        inList = /^\s{0,3}(?:[-*+]|\d+[.)])\s/.test(line);
      }
      const keep = /^\s*(?:-\s*){3,}$/.test(line) || isTableSeparator(line) || (indented && !inList);
      return keep ? line : convertDashes(line);
    }).join("\n");
  }))).join("");
}

// A table separator row (`|---|:--:|`): only pipes, dashes, colons, and
// spaces, with at least one pipe and one dash. Tested without a regex that
// backtracks, so a long line of ` -` stays linear.
function isTableSeparator(line) {
  return line.includes("|") && line.includes("-") && /^[\s:|-]*$/.test(line);
}

// Dashes outside inline code, link targets, autolinks, URLs (including
// www. hosts and mailto: addresses), email addresses, and HTML tags, whose
// attribute values keep their hyphens. Each alternative starts only where a
// run of its characters starts, so the split stays linear.
const PROTECTED_SPAN = new RegExp(`(${[
  "`[^`]*`",
  "\\]\\([^)\\s]*\\)",
  "<[a-z][a-z0-9+.-]*:[^>\\s]*>",
  "<\\/?[a-z][a-z0-9-]*(?:\\s[^<>]*)?\\/?>",
  "(?<![a-z0-9+.-])(?:[a-z][a-z0-9+.-]*:\\/\\/|mailto:)\\S+",
  "(?<![\\w.-])www\\.\\S+",
  "(?<![\\w.+-])[\\w.+-]+@[\\w-]+(?:\\.[\\w-]+)+"
].map((pattern) => `(?:${pattern})`).join("|")})`, "i");

function convertDashes(line) {
  return line.split(PROTECTED_SPAN).map((piece, index) => (index % 2 === 1
    ? piece
    : piece.replace(/(^|[^-])---(?!-)/g, "$1—").replace(/(^|[^-])--(?!-)/g, "$1–"))).join("");
}

// Applies `change` to the text outside HTML comments, scanning once.
function protectComments(text, change) {
  let result = "";
  let position = 0;
  while (position < text.length) {
    const open = text.indexOf("<!--", position);
    if (open === -1) {
      return result + change(text.slice(position));
    }
    const close = text.indexOf("-->", open + 4);
    if (close === -1) {
      // An unclosed comment still hides the rest from conversion.
      return result + change(text.slice(position, open)) + text.slice(open);
    }
    result += change(text.slice(position, open)) + text.slice(open, close + 3);
    position = close + 3;
  }
  return result;
}

// Splits on markdown chapter headings (`## Chapter 3: Title`, `# Prologue`,
// or a setext `Chapter One` underlined with `===` or `---`). A document with
// none is split on plain-text chapter lines instead: a numbered "Chapter"
// line, or a prologue or epilogue line, standing alone between blank lines,
// as in a manuscript saved as text. Lines inside code fences and HTML
// comments never split.
function splitByChapterHeadings(text) {
  const lines = text.split("\n");
  const hidden = hiddenLineIndexes(lines);
  const underlines = new Set();
  const markdownTitles = lines.map((line, index) => {
    if (hidden.has(index) || underlines.has(index)) {
      return null;
    }
    const setext = setextHeadingText(lines, index, hidden);
    const heading = setext ?? atxHeadingText(line);
    const title = heading === null ? null : chapterTitle(heading, CHAPTER_HEADING_PATTERN);
    if (title !== null && setext !== null) {
      underlines.add(index + 1);
    }
    return title;
  });
  const markdown = markdownTitles.some((title) => title !== null);
  const titles = markdown
    ? markdownTitles
    : lines.map((line, index) => (hidden.has(index) ? null : plainChapterTitle(lines, index)));
  const unused = unusedChapterLines(lines, hidden, titles, underlines);
  const sections = [];
  let current = null;
  const preamble = [];

  for (const [index, line] of lines.entries()) {
    const title = titles[index];
    if (title !== null) {
      // A part heading just before a chapter opens that chapter, rather than
      // ending the one before it or being dropped as the book title.
      const part = takePartHeading(current ? current.lines : preamble);
      if (current) {
        sections.push(finishChapter(current));
      }
      current = { title, lines: part, unnumbered: unnumberedHeading(lines, index, hidden, markdown) };
    } else if (markdown && underlines.has(index)) {
      continue;
    } else if (current) {
      current.lines.push(line);
    } else {
      preamble.push(line);
    }
  }

  if (!current) {
    return { sections: [], unused, markdown };
  }

  sections.push(finishChapter(current));
  const opening = stripTitleHeading(preamble.join("\n")).trim();
  // In a plain-text manuscript a lone short line before the first chapter is
  // the book title, the counterpart of a markdown `# Title`.
  const plainTitleOnly = markdown ? false : !opening.includes("\n") && opening.length <= PLAIN_LINE_MAX_LENGTH;
  if (opening !== "" && scanComments(opening).text.trim() === "") {
    // Comments alone are notes, not an Opening chapter: they stay at the top
    // of the first chapter, except the marker story export writes.
    const notes = opening.replace(GENERATED_MARKER, "").trim();
    if (notes !== "") {
      sections[0].prose = `${notes}\n\n${sections[0].prose}`.trim();
    }
  } else if (opening !== "" && !plainTitleOnly) {
    sections.unshift({ title: "Opening", prose: opening });
  }

  return { sections, unused, markdown };
}

// Numbered plain-text chapter lines (`Chapter 3`) that did not split, because
// the file has markdown chapter headings or the line does not stand alone
// between blank lines, so import can say the split did not happen.
function unusedChapterLines(lines, hidden, titles, underlines) {
  const unused = [];
  for (const [index, line] of lines.entries()) {
    const text = line.trim();
    if (titles[index] !== null || hidden.has(index) || underlines.has(index) || text.length > PLAIN_LINE_MAX_LENGTH) {
      continue;
    }
    if (PLAIN_CHAPTER_PATTERN.test(text)) {
      unused.push({ index, text });
    }
  }
  return unused;
}

// Removes a part heading (`# Part Two: Sea`), and the blank lines after it,
// from the end of `lines`, and returns the heading line.
function takePartHeading(lines) {
  let end = lines.length;
  while (end > 0 && lines[end - 1].trim() === "") {
    end -= 1;
  }
  const heading = end > 0 ? atxHeadingText(lines[end - 1]) : null;
  if (heading === null || !PART_HEADING.test(heading)) {
    return [];
  }
  return lines.splice(end - 1).slice(0, 1);
}

// Line indexes inside closed code fences or HTML comments.
function hiddenLineIndexes(lines) {
  const hidden = fencedLineIndexes(lines);
  let inComment = false;
  for (const [index, line] of lines.entries()) {
    if (hidden.has(index)) {
      continue;
    }
    if (inComment) {
      hidden.add(index);
    }
    // A `<!--` inside a code span is literal text.
    const text = line.replace(/`[^`]*`/g, "");
    let position = 0;
    for (;;) {
      const next = text.indexOf(inComment ? "-->" : "<!--", position);
      if (next === -1) {
        break;
      }
      position = next + (inComment ? 3 : 4);
      inComment = !inComment;
    }
  }
  return hidden;
}

// The text of an ATX heading (`## Chapter 2: Title ##`), without its closing
// hashes or a trailing Pandoc attribute block, or null. A lone `#` is a
// scene break, not a heading.
function atxHeadingText(line) {
  const heading = /^#{1,6}[ \t]+(\S.*)$/.exec(line);
  return heading ? cleanHeadingText(heading[1]) : null;
}

// The text of a one-line setext heading (a line underlined with `===` or
// `---`) standing after a blank line, or null.
function setextHeadingText(lines, index, hidden, underline = /^ {0,3}(?:=+|-+)[ \t]*$/) {
  const text = lines[index];
  const next = lines[index + 1];
  if (next === undefined || hidden.has(index + 1) || !underline.test(next) || text.trim() === "") {
    return null;
  }
  if (index > 0 && lines[index - 1].trim() !== "") {
    return null;
  }
  // Indented code, list items, quotes, headings, and dash lines are not
  // heading text.
  if (/^(?: {4}|\t)|^\s*(?:[-*+>#]|\d+[.)])(?:\s|$)/.test(text) || /^\s*(?:[-=*_]\s*)+$/.test(text)) {
    return null;
  }
  return cleanHeadingText(text);
}

// Drops a trailing Pandoc attribute block (`{#arrival .unnumbered}`) and
// closing hashes (`## Title ##`).
function cleanHeadingText(text) {
  return text
    .replace(/\s*\{[#.-][^{}]*\}\s*$/, "")
    .replace(/(?:^|[ \t]+)#+[ \t]*$/, "")
    .replace(/\s*\{[#.-][^{}]*\}\s*$/, "")
    .trim();
}

function plainChapterTitle(lines, index) {
  const text = lines[index].trim();
  const alone = (lines[index - 1] ?? "").trim() === "" && (lines[index + 1] ?? "").trim() === "";
  if (!alone || text === "" || text.length > PLAIN_LINE_MAX_LENGTH) {
    return null;
  }
  return chapterTitle(text, PLAIN_CHAPTER_PATTERN, PLAIN_SECTION_PATTERN);
}

// A chapter heading's title, "" for a bare numbered heading ("Chapter 1"),
// or null when the text is not a chapter heading.
function chapterTitle(text, pattern, sectionPattern = SECTION_HEADING_PATTERN) {
  if (sectionPattern.test(text)) {
    return text.replace(/[\s:.\-–—]+$/, "");
  }
  const match = pattern.exec(text);
  return match ? (match[1] ?? "").trim() : null;
}

function finishChapter(section) {
  return { title: section.title, prose: section.lines.join("\n").trim(), unnumbered: Boolean(section.unnumbered) };
}

// A Prologue, Epilogue, Interlude, or Afterword heading, or one Pandoc marks
// `{.unnumbered}` or `{-}`, builds with its title alone (`numbered: false`).
function unnumberedHeading(lines, index, hidden, markdown) {
  const line = lines[index];
  if (markdown && /\{[^{}]*(?:\.unnumbered|(?:^|[{\s])-(?=[\s}]))[^{}]*\}[\s#]*$/.test(line)) {
    return true;
  }
  const text = markdown ? setextHeadingText(lines, index, hidden) ?? atxHeadingText(line) : line.trim();
  return SECTION_HEADING_PATTERN.test(text ?? "");
}

// One chapter titled by the first `# ` heading outside code and comments,
// with any text before it kept, or by the file name.
function singleChapter(text, fileName) {
  const lines = text.split("\n");
  const hidden = hiddenLineIndexes(lines);
  const index = lines.findIndex((line, lineIndex) => !hidden.has(lineIndex) && /^#[ \t]+\S/.test(line));
  if (index !== -1) {
    const before = lines.slice(0, index).join("\n").trim();
    const after = lines.slice(index + 1).join("\n").trim();
    return {
      title: atxHeadingText(lines[index]),
      prose: [before, after].filter((part) => part !== "").join("\n\n")
    };
  }

  return {
    title: titleCaseSlug(path.basename(fileName, path.extname(fileName))),
    prose: text.trim()
  };
}

// Drops the book title before the first chapter: a leading `# Title` or a
// setext title underlined with `===`. A part heading is prose and stays.
function stripTitleHeading(text) {
  const lines = text.split("\n");
  const first = lines.findIndex((line) => line.trim() !== "");
  if (first === -1) {
    return text;
  }
  const atx = atxHeadingText(lines[first].trimStart());
  if (atx !== null && /^\s*#[ \t]/.test(lines[first])) {
    return PART_HEADING.test(atx) ? text : lines.slice(first + 1).join("\n");
  }
  if (setextHeadingText(lines, first, new Set(), /^ {0,3}=+[ \t]*$/) !== null) {
    return lines.slice(first + 2).join("\n");
  }
  return text;
}

function chapterMarkdown(title, number, words, prose, unnumbered = false) {
  return `${stringifyFrontmatter({
    title,
    number,
    ...(unnumbered ? { numbered: false } : {}),
    pov: "",
    locations: [],
    characters: [],
    "arcs-advanced": [],
    status: "draft",
    "word-count": words
  })}# ${unnumbered ? title : chapterHeading(number, title)}

## Chapter Text

${prose}
`;
}
