import { Buffer } from "node:buffer";
import fs from "node:fs";
import path from "node:path";
import { warn } from "./findings.js";
import { parseFrontmatter, stringifyFrontmatter, withoutLeadingFrontmatter } from "./frontmatter.js";
import { checkList, checkSet, isLanguageTag, languagePack, projectLanguage } from "./languages/index.js";
import { compareText, lowerCase } from "./languages/locale.js";
import { withStyleLists } from "./languages/style.js";
import { chapterHeading, characterCount, escapeRegExp, fencedLineIndexes, scanComments, splitFences, titleCaseSlug, wordCount } from "./markdown.js";
import { countUnit } from "./forms.js";
import { MAX_READ_BYTES, currentText, lstatIfExists, readFileBytes, removeFile } from "./files.js";
import { withProjectLock } from "./lock.js";
import { mirrorFolderNames } from "./preview.js";
import { buildLabels, nameList } from "./publishing.js";
import { SNAPSHOTS_DIR, nextSnapshotId, snapshotProject } from "./snapshots.js";
import { STDIN_ARG, decodeUtf8 } from "./stdin.js";
import { assertProjectParses, createStoryProject, existingStoryData, existingStoryLanguage, existingStyleData, newProjectRoot, reindexProject, scanProject, shellWord, writeFile } from "./story.js";
import { EXIT_CODES, exitCodeFor, refusedError, usageError, withDefaultExitCode } from "./exit-codes.js";

// A lone "I" before a word is the pronoun ("Chapter I Am Legend"), not a numeral.
const ROMAN_NUMERAL = "(?!i\\s+\\S)(?=[ivxlc])c{0,3}(?:xc|xl|l?x{0,3})(?:ix|iv|v?i{0,3})";
const PLAIN_LINE_MAX_LENGTH = 80;
// The comment story export and story build write under the book title.
const GENERATED_MARKER = /<!--\s*Generated by story (?:export|build)\.\s*-->/g;
const CANDIDATE_THRESHOLD = 3;
const CANDIDATE_LIMIT = 25;
const NEVER = "(?!)";
const RULES = new WeakMap();

// The heading patterns and candidate stopwords built from the language
// pack's words, once per pack. A pack without a list never matches it, so
// a manuscript in that language is never split on English headings.
function importRules(pack) {
  if (!RULES.has(pack)) {
    RULES.set(pack, buildImportRules(pack));
  }
  return RULES.get(pack);
}

function buildImportRules(pack) {
  const either = (name) => (checkList(pack, name) ?? []).map(listWord).join("|") || NEVER;
  const chapter = either("chapterWords");
  const section = either("sectionWords");
  // An arabic number may carry a decimal part ("Chapter 12.5").
  const chapterNumber = `(?:\\d+(?:\\.\\d+)?|${wordNumeral(checkList(pack, "numberWords"))}${ROMAN_NUMERAL})(?=[\\s:.\\-–—]|$)`;
  // In a pack with `ordinalWords`, an ordinal, or a number with a full
  // stop, may come before the heading word (Erstes Kapitel, 1. Kapitel,
  // Première partie).
  const ordinal = checkList(pack, "ordinalWords") === null ? null : `(?:\\d+\\.|(?:${either("ordinalWords")})(?![A-Za-z]))\\s+`;
  const ordinalFirst = (words, rest) => (ordinal === null ? "" : `|^${ordinal}(?:${words})(?![A-Za-z])${rest}`);
  return {
    chapterHeading: new RegExp(`^(?:${chapter})(?![A-Za-z])\\s*(?:${chapterNumber})?\\s*[:.\\-–—]*\\s*(.*)$${ordinalFirst(chapter, "\\s*[:.\\-–—]*\\s*(.*)$")}`, "i"),
    // A plain-text chapter line ("Chapter 3", "CHAPTER ONE: Arrival") must
    // carry a number and nothing else, or a separator before its title, so
    // a sentence such as "Chapter 12 was the worst." never splits.
    plainChapter: new RegExp(`^(?:${chapter})\\s+${chapterNumber}\\s*(?:[:.\\-–—]+\\s*(.*))?$${ordinalFirst(chapter, "\\s*(?:[:.\\-–—]+\\s*(.*))?$")}`, "i"),
    // Sections that are chapters in their own right but carry no number.
    sectionHeading: new RegExp(`^(?:${section})(?![A-Za-z])`, "i"),
    // As a plain line, the section name stands alone or before a separator.
    plainSection: new RegExp(`^(?:${section})\\s*(?:[:.\\-–—]+.*)?$`, "i"),
    // A part heading groups chapters; it is prose, never a chapter or the title.
    partHeading: new RegExp(`^${ordinal === null ? "" : `(?:${ordinal})?`}(?:${either("partWords")})(?![A-Za-z])`, "i"),
    frontMatter: new RegExp(`^(?:${either("frontMatterWords")})\\b`, "i"),
    candidateStopwords: new Set([...(checkList(pack, "candidateStopwords") ?? []), ...(checkList(pack, "calendarWords") ?? [])]),
    // For a language that capitalises its nouns; see extractNameCandidates.
    determiners: checkSet(pack, "determiners"),
    relativeWords: checkSet(pack, "relativeWords") ?? new Set(),
    nounSuffixes: checkList(pack, "nounSuffixes") ?? [],
    titleWords: checkSet(pack, "titleWords") ?? new Set(),
    // A speech verb next to a word ("sagte Lena", "Lena fragte") marks a
    // speaker, so a name.
    speechBefore: speechPattern(pack, (verbs) => `(?<![\\p{L}\\p{N}])(?:${verbs})\\s+$`),
    speechAfter: speechPattern(pack, (verbs) => `^\\s+(?:${verbs})(?![\\p{L}\\p{N}])`)
  };
}

function speechPattern(pack, shape) {
  const verbs = checkList(pack, "speechVerbs");
  return verbs === null || verbs.length === 0 ? null : new RegExp(shape(verbs.map(listWord).join("|")), "iu");
}

// A word-list entry as a pattern: an apostrophe matches a straight or
// curly one.
function listWord(word) {
  return escapeRegExp(word).replace(/'/g, "['’]");
}

// Spelled-out chapter numbers, as a pattern followed by `|`, or "" when the
// pack has no number words. English lists units, teens, tens, `hundred`,
// and `and`, for numbers below a thousand ("Chapter Twenty-One"). A pack
// whose numbers compound freely lists `words` and `joiners` instead: a
// numeral is any run of those words, joined by a space, a hyphen, nothing,
// or a joiner ("vingt et un", "quatre-vingt-dix", "einundzwanzig"). A pack
// may have both, as English does when a style sheet adds number words.
function wordNumeral(words) {
  if (words === null) {
    return "";
  }
  return `${words.units === undefined ? "" : unitNumeral(words)}${words.words === undefined ? "" : compoundNumeral(words)}`;
}

function compoundNumeral({ words, joiners = [] }) {
  // Longest first, so "dieciséis" is not read as "diez" and a title.
  const longestFirst = (list) => [...list].sort((left, right) => right.length - left.length || (left < right ? -1 : 1)).map(escapeRegExp).join("|");
  const word = `(?:${longestFirst(words) || NEVER})`;
  const joiner = joiners.length === 0 ? "" : `(?:(?:${longestFirst(joiners)})[-\\s]?)?`;
  return `${word}(?:[-\\s]?${joiner}${word})*|`;
}

function unitNumeral(words) {
  const units = words.units.join("|");
  const belowHundred = `(?:(?:${words.tens.join("|")})(?:[-\\s](?:${units}))?|${words.teens.join("|")}|${units})`;
  // Hundreds come first, so "One Hundred" is not read as "One" and a title.
  return `(?:(?:${units})[-\\s]${words.hundred}(?:(?:[-\\s]${words.and})?[-\\s]${belowHundred})?|${belowHundred})|`;
}

const MAX_IMPORT_FILE_BYTES = 5 * 1024 * 1024;
const MAX_IMPORT_FILES = 500;

function rejectSymlinkedSource(filePath) {
  if (fs.lstatSync(filePath).isSymbolicLink()) {
    throw usageError('Refusing to import symlinked source: ' + filePath);
  }
}

function assertImportFileSize(filePath) {
  const size = fs.statSync(filePath).size;
  if (size > MAX_IMPORT_FILE_BYTES) {
    throw usageError('Refusing to import oversized file ' + filePath + ': ' + size + ' bytes exceeds the ' + MAX_IMPORT_FILE_BYTES + ' byte limit');
  }
}

export function importManuscript(options) {
  const rawSource = String(options.source ?? "").trim();
  if (!rawSource) {
    throw usageError("An import source file or directory is required");
  }

  const cwd = options.cwd ?? process.cwd();
  // `-` reads the manuscript from stdin, as markdown; the caller reads it,
  // so this module does no I/O on stdin itself.
  const fromStdin = rawSource === STDIN_ARG;
  const source = fromStdin ? null : path.resolve(cwd, rawSource);
  if (!fromStdin && !fs.existsSync(source)) {
    throw usageError(`Import source not found: ${source}`);
  }
  // A story project's bible is not manuscript prose; importing it would turn
  // story.md and the style sheet into chapters.
  if (!fromStdin && fs.statSync(source).isDirectory() && fs.existsSync(path.join(source, "story.md"))) {
    throw usageError(`${rawSource} is already a story project (it has story.md); import reads manuscript files, so point it at the draft instead`);
  }

  // Heading words, number words, and candidate stopwords come from the
  // manuscript's language pack: --language, else the language of the
  // story.md being imported into, else English. A new story.md records an
  // explicit --language. The style sheet of a project being imported into
  // changes the lists with its `replace-words` and `add-words`.
  if (options.language !== undefined && !isLanguageTag(options.language)) {
    throw usageError(`--language ${options.language} must be a BCP 47 tag such as en, en-GB, or fr`);
  }
  const target = newProjectRoot({ title: options.title, cwd, dir: options.dir });
  // Piped text is read before the project lock is taken, so a slow pipe does
  // not hold it.
  const piped = fromStdin ? options.readStdin() : null;

  // --force into an existing folder snapshots, deletes, and rewrites its
  // chapters, so it holds the project lock from reading the project's
  // language, count unit, and style sheet to the reindex, as the other
  // write commands do: a command already running refuses this one before it
  // reads or changes anything, and the chapters are never built from
  // settings that changed meanwhile. A folder without story.md is locked
  // too, so two imports into it cannot interleave. A symlinked folder is
  // refused unlocked by createStoryProject, so no lock file is written
  // through it.
  const run = () => {
    const pack = withStyleLists(languagePack(options.language ?? (target === null ? null : existingStoryLanguage(target))), target === null ? null : existingStyleData(target));
    const rules = importRules(pack);
    const warnings = [];
    const documents = fromStdin
      ? [{ name: "stdin", path: "stdin", text: piped, untitled: true }]
      : readImportSource(source, rules);
    const existing = target === null ? null : existingStoryData(target);
    // --bylines reads a by-line as story export writes one for this book:
    // the language's labels, with a kept story.md's own `labels`.
    const bylines = options.bylines ? bylineReader(buildLabels(existing ?? {}, pack), rules) : null;
    const chapters = splitChapters(documents, warnings, rules, bylines);
    if (chapters.length === 0) {
      throw usageError("No chapter content found in import source");
    }

    // Build every chapter file before touching the disk: frontmatter and
    // headings make a chapter a little larger than its prose, and a file over
    // the size story reads would leave a project no command can open.
    // A book counted in characters (Chinese, Japanese, or story.md
    // `count-unit`) records character-count too, as story wordcount --write
    // does. An existing story.md is kept, so its count-unit and language
    // decide, whatever --language says.
    const characters = (existing === null ? countUnit(null, pack) : countUnit(existing, languagePack(projectLanguage(existing)))).name === "characters";
    let totalWords = 0;
    let totalCharacters = 0;
    const chapterFiles = chapters.map((chapter, index) => {
      const number = index + 1;
      // Count as the scanner does, without HTML comments.
      const prose = scanComments(chapter.prose).text;
      const words = wordCount(prose);
      const counts = characters ? { "word-count": words, "character-count": characterCount(prose) } : { "word-count": words };
      totalWords += words;
      totalCharacters += counts["character-count"] ?? 0;
      // An untitled numbered heading ("# Chapter 1") takes its new number.
      const title = chapter.title || `Chapter ${number}`;
      const name = `chapter-${String(number).padStart(2, "0")}.md`;
      const text = chapterMarkdown(title, number, counts, chapter.prose, chapter.unnumbered, chapter.authors);
      const bytes = Buffer.byteLength(text, "utf8");
      if (bytes > MAX_READ_BYTES) {
        throw usageError(`Cannot import: ${name} would be ${bytes} bytes, over the ${MAX_READ_BYTES} byte limit story reads. Split the manuscript with chapter headings first`);
      }
      return { name, text };
    });

    const projectOptions = {
      title: options.title,
      cwd,
      dir: options.dir,
      genre: options.genre,
      subGenre: options.subGenre,
      settingEra: options.settingEra,
      themes: options.themes,
      pov: options.pov,
      tense: options.tense,
      synopsis: options.synopsis,
      language: options.language,
      defaultSynopsis: `Imported from ${fromStdin ? "stdin" : path.basename(source)}. Replace with a 2-3 sentence synopsis.`,
      force: options.force,
      command: "story import --force",
      forceHint: "Use --force to import into it: --force saves the project as snapshot before-import-<n>, then deletes every chapters/chapter-NN.md and writes the imported chapters in their place, adds missing starter files, keeps story.md and the other files, and reindexes. story snapshot --restore before-import-<n> puts the old chapters back.",
      // Before anything is written: refuse a chapter entry the snapshot
      // cannot keep, check an existing project parses before deleting its
      // chapters, as the other mutating commands do (the chapter files about
      // to be replaced may be broken), and save the project as it is.
      beforeWrite(root, hasStory) {
        replaced = replacedChapters(root);
        if (!hasStory) {
          return;
        }
        let project;
        try {
          project = scanProject(root);
        } catch {
          // An unsafe layout (a symlinked folder, say) is refused by the
          // starter-file checks that follow, with their own message.
          return;
        }
        assertProjectParses(project, "import", (error) => /^chapters[\\/]chapter-\d+\.md$/i.test(error.file));
        if (replaced.length > 0) {
          snapshot = snapshotBeforeImport(root, cwd, options.preview);
        }
      }
    };
    let replaced = [];
    let snapshot = null;
    let created;
    try {
      created = createStoryProject(projectOptions);
      // A folder without story.md is saved once the starter files make it a
      // project, so the snapshot is a whole one restore can put back.
      if (snapshot === null && replaced.length > 0) {
        snapshot = snapshotBeforeImport(created.root, cwd, options.preview);
      }
      const chaptersDir = path.join(created.root, "chapters");
      for (const name of replaced) {
        // A chapter saved since the snapshot read it is left as saved.
        removeFile(path.join(chaptersDir, name), { root: created.root, unchangedFrom: currentText(path.join(created.root, snapshot.dir, "chapters", name)) });
      }

      for (const chapter of chapterFiles) {
        writeFile(path.join(chaptersDir, chapter.name), chapter.text, { root: created.root, unchangedFrom: null });
      }

      reindexProject(created.root);
    } catch (error) {
      if (snapshot === null) {
        throw error;
      }
      // Once the snapshot is saved, a failure names it, and exits as a
      // write that stopped part way, as a failed restore does.
      const code = exitCodeFor(error);
      error.exitCode = code === EXIT_CODES.findings ? EXIT_CODES.refused : code;
      throw withHint(error, `Snapshot ${snapshot.id} holds the project as it was before this import: ${snapshot.restore} puts it back`);
    }

    return {
      root: created.root,
      storyId: created.storyId,
      keptStory: created.keptStory,
      ignoredOptions: created.ignoredOptions,
      chapters: chapters.length,
      words: totalWords,
      ...(characters ? { characters: totalCharacters } : {}),
      warnings,
      gitignore: created.gitignore,
      snapshot,
      candidates: extractNameCandidates(chapters.map((chapter) => chapter.prose).join("\n\n"), pack)
    };
  };
  const locked = options.force && target !== null && lstatIfExists(target)?.isSymbolicLink() !== true;
  return locked ? withProjectLock(target, run, { folder: true }) : run();
}

// The chapter files --force replaces: every chapters/chapter-NN.md, in any
// letter case, so a folder that ignores case has the new files' names free.
// Each must be one the before-import snapshot keeps, a regular file whose
// name ends in .md as a scan reads it; anything else there would be deleted
// unsaved, so it is refused before the project changes.
function replacedChapters(root) {
  const folder = path.join(root, "chapters");
  const stats = lstatIfExists(folder);
  if (stats === null) {
    return [];
  }
  // A link or a file named chapters cannot be saved in the snapshot or
  // replaced, so it is refused before anything changes. A link is not
  // followed: its chapters are not the project's.
  if (!stats.isDirectory()) {
    const problem = stats.isSymbolicLink() ? "is a symlink" : "is not a folder";
    throw refusedError(`Cannot import: chapters ${problem}, so --force cannot save its chapters in a snapshot before replacing them. Replace it with a folder of chapter files, then import again. Nothing was changed`);
  }
  const entries = fs.readdirSync(folder, { withFileTypes: true }).filter((entry) => /^chapter-\d+\.md$/i.test(entry.name));
  for (const entry of entries) {
    const problem = entry.isSymbolicLink() ? "is a symlink"
      : entry.isDirectory() ? "is a folder"
        : !entry.isFile() ? "is not a regular file"
          : !entry.name.endsWith(".md") ? "does not end in lower-case .md"
            : null;
    if (problem !== null) {
      throw refusedError(`Cannot import: chapters/${entry.name} ${problem}, so the snapshot import --force takes before replacing the chapters cannot keep it, and --force would delete it. Rename, move, or delete it, then import again. Nothing was changed`);
    }
  }
  return entries.map((entry) => entry.name).sort();
}

// The chapters --force deletes are kept first, under the project lock, in
// snapshot before-import-<n> (one more than the highest n already taken),
// so `story snapshot --restore` puts them back. It holds every markdown
// file a scan reads, a chapter that does not parse included. A snapshot
// that cannot be saved (a chapter that is not UTF-8 text, a full disk)
// stops the import before any chapter is deleted. A --dry-run runs on a
// copy of the folder, `preview.root`, which leaves out .snapshots/: the
// folder is made in the copy as the project has it first, so the copy
// numbers the snapshot, and refuses it, as the project would.
function snapshotBeforeImport(root, cwd, preview) {
  let id = "before-import-<n>";
  try {
    if (preview?.root) {
      mirrorFolderNames(path.join(preview.root, SNAPSHOTS_DIR), path.join(root, SNAPSHOTS_DIR));
    }
    id = nextSnapshotId(root, "before-import-");
    const snapshot = snapshotProject(root, { name: id, id, unparsed: true });
    return { id: snapshot.id, dir: snapshot.dir, restore: restoreCommand(cwd, preview?.root ?? root, snapshot.id) };
  } catch (error) {
    throw withHint(error, `The import stopped before deleting any chapter: it could not save the project as snapshot ${id} first`);
  }
}

// The command that puts the project back as snapshot `id` holds it, with
// the project's path from where import ran (none from inside it).
function restoreCommand(cwd, root, id) {
  const where = path.relative(cwd, root).split(path.sep).join("/");
  return `story snapshot --restore ${id}${where === "" ? "" : ` --path ${shellWord(where)}`}`;
}

// Adds a sentence after the error's message and any hint it has.
function withHint(error, hint) {
  error.hint = typeof error.hint === "string" ? `${error.hint}. ${hint}` : hint;
  return error;
}

// A capitalised name word in any script: "Élodie", "O’Brien", "McAllister",
// "Anna-Maria", "King’s". Curly and straight apostrophes both count.
const NAME_WORD = "(?:(?:Ma?c|[OD]['’])(?=\\p{Lu}))?\\p{Lu}\\p{Ll}+(?:['’]\\p{Ll}+)?(?:-\\p{Lu}\\p{Ll}+)*";
const NAME_RUN_PATTERN = new RegExp(`(?<![\\p{L}\\p{N}'’-])${NAME_WORD}(?:\\s+${NAME_WORD})+(?![\\p{L}\\p{N}])`, "gu");
// A single name word, not part of a run of capitalised words.
const NAME_SINGLE_PATTERN = new RegExp(`(?<![\\p{L}\\p{N}'’-])(?<!${NAME_WORD}\\s+)${NAME_WORD}(?![\\p{L}\\p{N}])(?!\\s+${NAME_WORD})`, "gu");
// After a lowercase word, mid-sentence, a capitalised word is a name.
const MID_SENTENCE = /\p{Ll}[,;:]?\s$/u;
// A word with a capital inside (McAllister, O’Brien, Anna-Maria) is a name
// even where a sentence starts.
const DISTINCTIVE_NAME = /^\p{Lu}.*\p{Lu}/u;

// In a language that capitalises every noun (German), a pack lists
// `determiners` and `nounSuffixes`. A single word that follows a
// determiner (die Tür, der alte Hund) in at least a third of its uses, or
// ends like a noun (Hoffnung) and follows one at least once, is a common
// noun, not a name; a name is seldom set after an article (die kleine
// Anna), so an occasional one keeps it. A word that ever follows a title
// (Herr Jung) or stands next to a speech verb (sagte Gretchen) is a name
// whatever else it does, since spoken German sets articles before names
// (den Peter).
const DETERMINED_SHARE = 1 / 3;

export function extractNameCandidates(prose, pack = languagePack()) {
  const rules = importRules(pack);
  const stopwords = rules.candidateStopwords;
  const counts = new Map();
  const determined = new Map();
  const named = new Set();
  const nounRule = rules.determiners !== null;
  const speaks = (index, end) => (rules.speechBefore !== null && rules.speechBefore.test(prose.slice(Math.max(0, index - 40), index)))
    || (rules.speechAfter !== null && rules.speechAfter.test(prose.slice(end, end + 40)));

  for (const match of prose.matchAll(NAME_RUN_PATTERN)) {
    const words = match[0].replace(/\s+/g, " ").split(" ");
    let article = false;
    let titled = false;
    while (words.length > 0 && (stopwords.has(straight(words[0])) || (nounRule && rules.determiners.has(lowerCase(words[0], pack))))) {
      const word = lowerCase(words[0], pack);
      const determiner = nounRule && rules.determiners.has(word);
      article ||= determiner;
      // Title words include the articles (der, die); only a real title
      // (Herr, Frau, Dr) marks a name.
      titled ||= !determiner && rules.titleWords.has(word.replace(/\.$/, ""));
      words.shift();
    }
    if (words.length > 0) {
      const name = withoutPossessive(words.join(" "));
      addCandidate(counts, name);
      if (nounRule && words.length === 1) {
        if (titled || speaks(match.index, match.index + match[0].length)) {
          named.add(name);
        } else if (article || afterDeterminer(prose, match.index, rules, pack)) {
          addCandidate(determined, name);
        }
      }
    }
  }

  for (const match of prose.matchAll(NAME_SINGLE_PATTERN)) {
    const name = withoutPossessive(match[0]);
    if (stopwords.has(straight(name))) {
      continue;
    }
    if (nounRule && speaks(match.index, match.index + match[0].length)) {
      named.add(name);
    }
    if (DISTINCTIVE_NAME.test(name) || MID_SENTENCE.test(prose.slice(Math.max(0, match.index - 3), match.index))) {
      addCandidate(counts, name);
      if (nounRule && afterDeterminer(prose, match.index, rules, pack)) {
        addCandidate(determined, name);
      }
    }
  }

  const commonNoun = (name, count) => {
    const articles = determined.get(name) ?? 0;
    return nounRule && !name.includes(" ") && !named.has(name)
      && (articles >= count * DETERMINED_SHARE || (articles > 0 && rules.nounSuffixes.some((suffix) => lowerCase(name, pack).endsWith(suffix))));
  };
  return [...counts.entries()]
    .filter(([name, count]) => count >= CANDIDATE_THRESHOLD && !commonNoun(name, count))
    .sort((left, right) => right[1] - left[1] || compareText(pack)(left[0], right[0]))
    .slice(0, CANDIDATE_LIMIT)
    .map(([name, count]) => ({ name, count }));
}

// Whether the word at `index` follows a determiner, with up to two
// lower-case words between ("die Tür", "der alte graue Hund"). Only spaces
// may separate them: a comma or full stop ends the phrase. A determiner
// that is also a relative pronoun starts a clause after a comma (die
// Frau, die Lena kannte), so it does not count there.
const PHRASE_BEFORE = /(?<![\p{L}\p{M}'’-])(?:[\p{L}\p{M}'’-]+\s+){1,3}$/u;

function afterDeterminer(prose, index, rules, pack) {
  const before = prose.slice(Math.max(0, index - 80), index);
  const phrase = PHRASE_BEFORE.exec(before);
  if (phrase === null) {
    return false;
  }
  const words = phrase[0].trim().split(/\s+/);
  for (let position = words.length - 1; position >= 0; position -= 1) {
    const word = lowerCase(words[position], pack);
    if (rules.determiners.has(word)) {
      return !(position === 0 && rules.relativeWords.has(word) && /,\s*$/.test(before.slice(0, phrase.index)));
    }
    if (!/^\p{Ll}/u.test(words[position])) {
      return false;
    }
  }
  return false;
}

// Stopwords are listed with a straight apostrophe (Qu'il).
function straight(word) {
  return word.replace(/’/g, "'");
}

// "Élodie’s" counts as "Élodie"; "King’s Road" keeps its inner possessive.
function withoutPossessive(name) {
  return name.replace(/['’]s$/, "");
}

function addCandidate(counts, name) {
  counts.set(name, (counts.get(name) ?? 0) + 1);
}

// Reads a source file as UTF-8 text without its byte-order mark. A zip
// (such as .docx), a binary file, or text in another encoding is refused, so
// no character is silently replaced. readSourceDocuments has already
// refused a symlink or an oversized file; the read refuses one swapped in
// since.
function readSourceText(filePath) {
  return decodeUtf8(readFileBytes(filePath, MAX_IMPORT_FILE_BYTES), `Cannot import ${filePath}`, "Save it as UTF-8 plain text or markdown first");
}

// The source is an argument, so a source that cannot be read (permission
// denied, say) is a usage error, not a broken story project.
function readImportSource(source, rules) {
  try {
    return readSourceDocuments(source, rules);
  } catch (error) {
    throw withDefaultExitCode(error, EXIT_CODES.usage);
  }
}

function readSourceDocuments(source, rules) {
  rejectSymlinkedSource(source);
  if (fs.statSync(source).isFile()) {
    assertImportFileSize(source);
    return [{ name: path.basename(source), path: source, text: readSourceText(source) }];
  }

  const names = [];
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const fullPath = path.join(source, entry.name);
    if (fs.lstatSync(fullPath).isSymbolicLink()) {
      // Never follow symlinks during import. A symlink that resolves to an
      // importable document is rejected loudly; anything else (subdirectory
      // links, dangling links) is skipped so stray links cannot block a
      // safe import.
      let targetIsDocument = false;
      try {
        targetIsDocument = fs.statSync(fullPath).isFile();
      } catch {
        targetIsDocument = false;
      }
      if (targetIsDocument && /\.(md|markdown|txt)$/i.test(entry.name)) {
        rejectSymlinkedSource(fullPath);
      }
      continue;
    }
    // Hidden files, macOS AppleDouble files (._name), and Word lock files
    // (~$name) are copies or droppings, not chapters.
    if (entry.isFile() && /\.(md|markdown|txt)$/i.test(entry.name) && !/^(?:\.|~\$)/.test(entry.name)) {
      names.push(entry.name);
    }
  }
  names.sort((left, right) => compareImportNames(left, right, rules));
  if (names.length > MAX_IMPORT_FILES) {
    throw usageError('Too many import files in ' + source + ': ' + names.length + ' exceeds the ' + MAX_IMPORT_FILES + ' file limit');
  }
  const documents = names.map((name) => {
    const fullPath = path.join(source, name);
    assertImportFileSize(fullPath);
    return { name, path: fullPath, text: readSourceText(fullPath) };
  });

  if (documents.length === 0) {
    throw usageError(`No markdown or text files found in ${source}`);
  }

  return documents;
}

// Numbered files sort numerically. Unnumbered files sort after them, except
// front matter such as a prologue, which sorts first.
function importNameRank(name, nums, rules) {
  if (nums.length > 0) {
    return 1;
  }
  return rules.frontMatter.test(name) ? 0 : 2;
}

export function compareImportNames(left, right, rules = importRules(languagePack())) {
  const leftNums = [...left.matchAll(/\d+/g)].map((match) => Number(match[0]));
  const rightNums = [...right.matchAll(/\d+/g)].map((match) => Number(match[0]));
  const rankDiff = importNameRank(left, leftNums, rules) - importNameRank(right, rightNums, rules);
  if (rankDiff !== 0) {
    return rankDiff;
  }
  const length = Math.max(leftNums.length, rightNums.length);
  for (let index = 0; index < length; index += 1) {
    const leftNum = leftNums[index];
    const rightNum = rightNums[index];
    if (leftNum === undefined) {
      return -1;
    }
    if (rightNum === undefined) {
      return 1;
    }
    if (leftNum !== rightNum) {
      return leftNum - rightNum;
    }
  }
  if (left === right) {
    return 0;
  }
  return left < right ? -1 : 1;
}

function splitChapters(documents, warnings, rules, bylines) {
  const chapters = [];

  for (const document of documents) {
    // A bare CR (classic Mac OS) ends a line too.
    const source = document.text.replace(/\r\n?/g, "\n");
    const own = storySkillsChapter(source);
    if (own) {
      if (own.skipped.length > 0) {
        const [first] = own.skipped;
        const count = own.skipped.length === 1 ? "1 line above ## Chapter Text was" : `${own.skipped.length} lines above ## Chapter Text were`;
        warnings.push({ ...warn("unused-chapter-text", `${document.name}: ${count} not imported (first "${first.text}" at line ${first.line}): a chapter file's prose is only the text under ## Chapter Text. Keep any other text below that heading`), source: document.path });
      }
      // Its own `author` comes first: --bylines reads a by-line only when it has none.
      chapters.push(bylines === null || own.authors.length > 0 ? own : withBylines([own], [], bylines)[0]);
      continue;
    }
    const body = withoutLeadingFrontmatter(source);
    // Line numbers in warnings count from the top of the file, frontmatter
    // included.
    const offset = source.slice(0, source.length - body.length).split("\n").length - 1;
    const text = normalizeSource(body, document.name);
    const { sections, unused, markdown, authors } = splitByChapterHeadings(text, rules, bylines);
    if (unused.length > 0) {
      const count = unused.length === 1 ? "1 plain-text chapter line was" : `${unused.length} plain-text chapter lines were`;
      const why = markdown
        ? "the file has markdown chapter headings, which take precedence, so make these headings too (## Chapter 1)"
        : "a chapter line splits only when it stands alone between blank lines, so add a blank line after each";
      // The finding is about the manuscript, not a project file, so it
      // names the manuscript file as its source: its absolute path, or
      // stdin.
      warnings.push({ ...warn("unsplit-chapter-lines", `${document.name}: ${count} not used to split chapters (first "${unused[0].text}" at line ${unused[0].index + 1 + offset}): ${why}. See "How chapters are split" in docs/manuscripts.md`), source: document.path });
    }
    const found = sections.length > 0 ? sections : [singleChapter(text, document)];
    chapters.push(...(bylines === null ? found : withBylines(found, authors.length > 0 ? authors : frontmatterAuthors(source, body), bylines)));
  }

  // A chapter whose prose was only its by-line is still a story, such as an
  // exported chapter with no text yet.
  return chapters.filter((chapter) => chapter.prose !== "" || chapter.bylined);
}

// The frontmatter keys a Story Skills chapter file has. `title` and `author`
// are not among them, since a manuscript has them too.
const CHAPTER_KEYS = ["number", "numbered", "pov", "locations", "characters", "arcs-advanced", "status"];

// A chapter file in Story Skills' own layout, copied from another project,
// keeps its title, `numbered: false`, and `author`, and its prose is the
// text under `## Chapter Text` (the outline above it is not book text). Only
// a file with a chapter key such as `number` is one: a manuscript with
// frontmatter of its own and a `## Chapter Text` heading is split as
// markdown. `skipped` lists the lines above the heading that are not used,
// as { text, line }.
function storySkillsChapter(text) {
  const heading = /^## Chapter Text[ \t]*$/m.exec(text);
  if (!heading) {
    return null;
  }
  let parsed;
  try {
    parsed = parseFrontmatter(text);
  } catch {
    return null;
  }
  const { data } = parsed;
  if (!CHAPTER_KEYS.some((key) => Object.hasOwn(data, key))) {
    return null;
  }
  const title = typeof data.title === "string" || typeof data.title === "number" ? String(data.title).replace(/\s+/g, " ").trim() : "";
  // The body is the end of the text, so it starts where the frontmatter ends.
  const bodyStart = text.length - parsed.body.length;
  const firstLine = text.slice(0, bodyStart).split("\n").length;
  const lines = text.slice(bodyStart, heading.index).split("\n")
    .map((line, index) => ({ text: line.trim(), line: firstLine + index }))
    .filter((line) => line.text !== "");
  const outline = outlineLines(lines);
  // A `# ` line is the chapter's heading, which the chapter takes from its title.
  const skipped = lines.filter((line) => !outline.has(line) && !/^#[ \t]/.test(line.text));
  return { title, prose: text.slice(heading.index + heading[0].length).trim(), unnumbered: data.numbered === false, authors: importedNames(data.author), skipped };
}

// The outline that story add chapter writes above `## Chapter Text`: its
// `## Outline` heading through the `---` divider after it, or to the end
// when there is no divider. It is planning, not book text, so it is not
// reported as unused. Takes the non-blank lines, as { text, line }.
function outlineLines(lines) {
  const start = lines.findIndex((line) => /^##[ \t]+Outline$/i.test(line.text));
  if (start === -1) {
    return new Set();
  }
  const divider = lines.findIndex((line, index) => index > start && line.text === "---");
  return new Set(lines.slice(start, divider === -1 ? lines.length : divider + 1));
}

// A name field's names, each on one line, so a line break in one cannot
// start a new paragraph where story export writes the byline.
function importedNames(value) {
  return nameList(value).map((name) => name.replace(/\s+/g, " "));
}

// --bylines: each chapter's author is the by-line opening its prose, taken
// out of the prose, else `authors`: the by-line before the file's first
// chapter heading, or the file's frontmatter `author`.
function withBylines(sections, authors, bylines) {
  return sections.map((section) => {
    const read = leadingByline(section.prose, section.titleLine === true, bylines);
    return read === null ? { ...section, authors } : { ...section, prose: read.text, authors: read.authors, bylined: true };
  });
}

// The names in a source file's frontmatter `author`, or none when it has no
// frontmatter or frontmatter the CLI's parser rejects.
function frontmatterAuthors(source, body) {
  if (body === source) {
    return [];
  }
  try {
    return importedNames(parseFrontmatter(source).data.author);
  } catch {
    return [];
  }
}

// What a by-line looks like in this book: the words the `byline` label
// puts before the names (by, par, von), and the `and` label's words
// between two names, as joinNames writes them. A language that writes a
// byline as the names alone has no by-line to read (`pattern` is null).
function bylineReader(labels, rules) {
  const [before, after = null] = labels.byline.split("{names}");
  const word = before.trim();
  const and = labels.and.includes("{a}") && labels.and.includes("{b}") ? labels.and : "{a}, {b}";
  const joiner = /^\{a\}(.*\S.*)\{b\}$/su.exec(and)?.[1];
  const space = (text) => (/\s/.test(text) ? "\\s+" : "\\s*");
  return {
    pattern: word === "" || after === null || after.trim() !== "" ? null : new RegExp(`^${escapeRegExp(word)}[\\s:]+(.+)$`, "iu"),
    joiner: joiner === undefined ? null : new RegExp(`${space(joiner[0])}${escapeRegExp(joiner.trim())}${space(joiner.at(-1))}`, "iu"),
    stopwords: rules.candidateStopwords
  };
}

// The by-line opening `text`: its first paragraph, or with `titleLine` (a
// plain-text title before it) the paragraph after a short first line. It
// is { text without it, authors }, or null when there is none.
function leadingByline(text, titleLine, bylines) {
  const parts = text.split(/(\n[ \t]*\n)/);
  const tries = titleLine && parts.length > 2 && isTitleLine(parts[0]) ? [0, 1] : [0];
  for (const index of tries) {
    const authors = bylineAuthors(parts[index * 2].trim(), bylines);
    if (authors.length > 0) {
      parts.splice(index * 2, 2);
      return { text: parts.join("").trim(), authors };
    }
  }
  return null;
}

function isTitleLine(text) {
  return !text.trim().includes("\n") && text.trim().length <= PLAIN_LINE_MAX_LENGTH;
}

// The names in a by-line paragraph ("By Ada Writer", "*by Ada Writer and
// Ben Other*" as story export writes it), or none. When unsure it is
// prose: a missed by-line is set by hand, deleted prose is lost.
function bylineAuthors(paragraph, bylines) {
  const line = withoutEmphasis(paragraph);
  const match = bylines.pattern === null || line.includes("\n") || line.length > PLAIN_LINE_MAX_LENGTH ? null : bylines.pattern.exec(line);
  if (match === null) {
    return [];
  }
  const names = (bylines.joiner === null ? [match[1]] : match[1].split(bylines.joiner)).map((name) => withoutEmphasis(name).replace(/\s+/g, " "));
  return names.every((name) => isBylineName(name, bylines.stopwords)) ? names : [];
}

// A name: two to six words, each starting with a letter that is not lower
// case ("Ada", "O’Brien", "Anna-Maria"), an initial ("J.", "J.R.R."), or a
// short abbreviation ("Jr."), with lower-case particles ("van", "de")
// between them. No digits, quotes, commas, or other punctuation, and no
// stopword or calendar word, so "By God, it was me.", "By Christmas he
// was at sea.", "By Monday the toll had reached 40.", and "Von Osten her."
// stay prose.
const BYLINE_WORD = /^(?:(?:\p{Lu}\.)+|\p{Lu}\p{Ll}\.|(?!\p{Ll})\p{L}[\p{L}\p{M}]*(?:['’-][\p{L}\p{M}]+)*)$/u;
const NAME_PARTICLES = new Set(["al", "bin", "da", "das", "de", "del", "della", "den", "der", "des", "di", "do", "dos", "du", "ibn", "la", "le", "ten", "ter", "van", "von", "y", "zu"]);

function isBylineName(name, stopwords) {
  const words = name.split(" ");
  return words.length >= 2 && words.length <= 6 && words.every((word, index) => !stopwords.has(straight(word))
    && (BYLINE_WORD.test(word) || (index > 0 && index < words.length - 1 && NAME_PARTICLES.has(word))));
}

function withoutEmphasis(text) {
  return text.trim().replace(/^([*_]{1,2})(.+)\1$/, "$2").trim();
}

// Markdown from Pandoc spells an em dash `---` and an en dash `--`, so a
// markdown source gets real dashes (outside code). Plain text has no markdown
// indentation, so leading tabs and spaces (a Scrivener paragraph indent) are
// dropped rather than turning paragraphs into code blocks.
function normalizeSource(text, name) {
  if (/\.te?xt$/i.test(name)) {
    return text.replace(/^[ \t]+/gm, "");
  }
  // Code, HTML comments, link targets and URLs, table separator rows,
  // indented code, and lines of only dashes (scene breaks) keep their hyphens.
  return splitFences(text).map((part) => (part.fenced ? part.text : protectComments(part.text, (prose) => {
    // An indented line is code, unless it continues a list item.
    let inList = false;
    return prose.split("\n").map((line) => {
      const indented = /^(?: {4}|\t)/.test(line);
      if (!indented && line.trim() !== "") {
        inList = /^\s{0,3}(?:[-*+]|\d+[.)])\s/.test(line);
      }
      const keep = /^\s*(?:-\s*){3,}$/.test(line) || isTableSeparator(line) || (indented && !inList);
      return keep ? line : convertDashes(line);
    }).join("\n");
  }))).join("");
}

// A table separator row (`|---|:--:|`): only pipes, dashes, colons, and
// spaces, with at least one pipe and one dash. Tested without a regex that
// backtracks, so a long line of ` -` stays linear.
function isTableSeparator(line) {
  return line.includes("|") && line.includes("-") && /^[\s:|-]*$/.test(line);
}

// Dashes outside inline code, link targets, autolinks, URLs (including
// www. hosts and mailto: addresses), email addresses, and HTML tags, whose
// attribute values keep their hyphens. Each alternative starts only where a
// run of its characters starts, so the split stays linear.
const PROTECTED_SPAN = new RegExp(`(${[
  "`[^`]*`",
  "\\]\\([^)\\s]*\\)",
  "<[a-z][a-z0-9+.-]*:[^>\\s]*>",
  "<\\/?[a-z][a-z0-9-]*(?:\\s[^<>]*)?\\/?>",
  "(?<![a-z0-9+.-])(?:[a-z][a-z0-9+.-]*:\\/\\/|mailto:)\\S+",
  "(?<![\\w.-])www\\.\\S+",
  "(?<![\\w.+-])[\\w.+-]+@[\\w-]+(?:\\.[\\w-]+)+"
].map((pattern) => `(?:${pattern})`).join("|")})`, "i");

function convertDashes(line) {
  return line.split(PROTECTED_SPAN).map((piece, index) => (index % 2 === 1
    ? piece
    : piece.replace(/(^|[^-])---(?!-)/g, "$1—").replace(/(^|[^-])--(?!-)/g, "$1–"))).join("");
}

// Applies `change` to the text outside HTML comments, scanning once.
function protectComments(text, change) {
  let result = "";
  let position = 0;
  while (position < text.length) {
    const open = text.indexOf("<!--", position);
    if (open === -1) {
      return result + change(text.slice(position));
    }
    const close = text.indexOf("-->", open + 4);
    if (close === -1) {
      // An unclosed comment still hides the rest from conversion.
      return result + change(text.slice(position, open)) + text.slice(open);
    }
    result += change(text.slice(position, open)) + text.slice(open, close + 3);
    position = close + 3;
  }
  return result;
}

// Splits on markdown chapter headings (`## Chapter 3: Title`, `# Prologue`,
// or a setext `Chapter One` underlined with `===` or `---`). A document with
// none is split on plain-text chapter lines instead: a numbered "Chapter"
// line, or a prologue or epilogue line, standing alone between blank lines,
// as in a manuscript saved as text. Lines inside code fences and HTML
// comments never split.
function splitByChapterHeadings(text, rules, bylines) {
  const lines = text.split("\n");
  const hidden = hiddenLineIndexes(lines);
  const underlines = new Set();
  const markdownTitles = lines.map((line, index) => {
    if (hidden.has(index) || underlines.has(index)) {
      return null;
    }
    const setext = setextHeadingText(lines, index, hidden);
    const heading = setext ?? atxHeadingText(line);
    const title = heading === null ? null : chapterTitle(heading, rules.chapterHeading, rules.sectionHeading);
    if (title !== null && setext !== null) {
      underlines.add(index + 1);
    }
    return title;
  });
  const markdown = markdownTitles.some((title) => title !== null);
  const titles = markdown
    ? markdownTitles
    : lines.map((line, index) => (hidden.has(index) ? null : plainChapterTitle(lines, index, rules)));
  const unused = unusedChapterLines(lines, hidden, titles, underlines, rules);
  const sections = [];
  let current = null;
  const preamble = [];

  for (const [index, line] of lines.entries()) {
    const title = titles[index];
    if (title !== null) {
      // A part heading just before a chapter opens that chapter, rather than
      // ending the one before it or being dropped as the book title.
      const part = takePartHeading(current ? current.lines : preamble, rules);
      if (current) {
        sections.push(finishChapter(current));
      }
      current = { title, lines: part, unnumbered: unnumberedHeading(lines, index, hidden, markdown, rules) };
    } else if (markdown && underlines.has(index)) {
      continue;
    } else if (current) {
      current.lines.push(line);
    } else {
      preamble.push(line);
    }
  }

  if (!current) {
    return { sections: [], unused, markdown, authors: [] };
  }

  sections.push(finishChapter(current));
  let opening = stripTitleHeading(preamble.join("\n"), rules).trim();
  // --bylines: a by-line under the title, before the first chapter, credits
  // the file's chapters.
  const credit = bylines === null ? null : leadingByline(opening, !markdown, bylines);
  if (credit !== null) {
    opening = credit.text;
  }
  // In a plain-text manuscript a lone short line before the first chapter is
  // the book title, the counterpart of a markdown `# Title`.
  const plainTitleOnly = markdown ? false : !opening.includes("\n") && opening.length <= PLAIN_LINE_MAX_LENGTH;
  if (opening !== "" && scanComments(opening).text.trim() === "") {
    // Comments alone are notes, not an Opening chapter: they stay at the top
    // of the first chapter, except the marker story export writes.
    const notes = opening.replace(GENERATED_MARKER, "").trim();
    if (notes !== "") {
      sections[0].prose = `${notes}\n\n${sections[0].prose}`.trim();
    }
  } else if (opening !== "" && !plainTitleOnly) {
    sections.unshift({ title: "Opening", prose: opening });
  }

  return { sections, unused, markdown, authors: credit?.authors ?? [] };
}

// Numbered plain-text chapter lines (`Chapter 3`) that did not split, because
// the file has markdown chapter headings or the line does not stand alone
// between blank lines, so import can say the split did not happen.
function unusedChapterLines(lines, hidden, titles, underlines, rules) {
  const unused = [];
  for (const [index, line] of lines.entries()) {
    const text = line.trim();
    if (titles[index] !== null || hidden.has(index) || underlines.has(index) || text.length > PLAIN_LINE_MAX_LENGTH) {
      continue;
    }
    if (rules.plainChapter.test(text)) {
      unused.push({ index, text });
    }
  }
  return unused;
}

// Removes a part heading (`# Part Two: Sea`), and the blank lines after it,
// from the end of `lines`, and returns the heading line.
function takePartHeading(lines, rules) {
  let end = lines.length;
  while (end > 0 && lines[end - 1].trim() === "") {
    end -= 1;
  }
  const heading = end > 0 ? atxHeadingText(lines[end - 1]) : null;
  if (heading === null || !rules.partHeading.test(heading)) {
    return [];
  }
  return lines.splice(end - 1).slice(0, 1);
}

// Line indexes inside closed code fences or HTML comments.
function hiddenLineIndexes(lines) {
  const hidden = fencedLineIndexes(lines);
  let inComment = false;
  for (const [index, line] of lines.entries()) {
    if (hidden.has(index)) {
      continue;
    }
    if (inComment) {
      hidden.add(index);
    }
    // A `<!--` inside a code span is literal text.
    const text = line.replace(/`[^`]*`/g, "");
    let position = 0;
    for (;;) {
      const next = text.indexOf(inComment ? "-->" : "<!--", position);
      if (next === -1) {
        break;
      }
      position = next + (inComment ? 3 : 4);
      inComment = !inComment;
    }
  }
  return hidden;
}

// The text of an ATX heading (`## Chapter 2: Title ##`), without its closing
// hashes or a trailing Pandoc attribute block, or null. A lone `#` is a
// scene break, not a heading.
function atxHeadingText(line) {
  const heading = /^#{1,6}[ \t]+(\S.*)$/.exec(line);
  return heading ? cleanHeadingText(heading[1]) : null;
}

// The text of a one-line setext heading (a line underlined with `===` or
// `---`) standing after a blank line, or null.
function setextHeadingText(lines, index, hidden, underline = /^ {0,3}(?:=+|-+)[ \t]*$/) {
  const text = lines[index];
  const next = lines[index + 1];
  if (next === undefined || hidden.has(index + 1) || !underline.test(next) || text.trim() === "") {
    return null;
  }
  if (index > 0 && lines[index - 1].trim() !== "") {
    return null;
  }
  // Indented code, list items, quotes, headings, and dash lines are not
  // heading text.
  if (/^(?: {4}|\t)|^\s*(?:[-*+>#]|\d+[.)])(?:\s|$)/.test(text) || /^\s*(?:[-=*_]\s*)+$/.test(text)) {
    return null;
  }
  return cleanHeadingText(text);
}

// Drops a trailing Pandoc attribute block (`{#arrival .unnumbered}`) and
// closing hashes (`## Title ##`).
function cleanHeadingText(text) {
  return text
    .replace(/\s*\{[#.-][^{}]*\}\s*$/, "")
    .replace(/(?:^|[ \t]+)#+[ \t]*$/, "")
    .replace(/\s*\{[#.-][^{}]*\}\s*$/, "")
    .trim();
}

function plainChapterTitle(lines, index, rules) {
  const text = lines[index].trim();
  const alone = (lines[index - 1] ?? "").trim() === "" && (lines[index + 1] ?? "").trim() === "";
  if (!alone || text === "" || text.length > PLAIN_LINE_MAX_LENGTH) {
    return null;
  }
  return chapterTitle(text, rules.plainChapter, rules.plainSection);
}

// A chapter heading's title, "" for a bare numbered heading ("Chapter 1"),
// or null when the text is not a chapter heading.
function chapterTitle(text, pattern, sectionPattern) {
  if (sectionPattern.test(text)) {
    return text.replace(/[\s:.\-–—]+$/, "");
  }
  const match = pattern.exec(text);
  // An ordinal-first heading (Erstes Kapitel: Titel) captures its title second.
  return match ? (match[1] ?? match[2] ?? "").trim() : null;
}

function finishChapter(section) {
  return { title: section.title, prose: section.lines.join("\n").trim(), unnumbered: Boolean(section.unnumbered) };
}

// A Prologue, Epilogue, Interlude, or Afterword heading, or one Pandoc marks
// `{.unnumbered}` or `{-}`, builds with its title alone (`numbered: false`).
function unnumberedHeading(lines, index, hidden, markdown, rules) {
  const line = lines[index];
  if (markdown && /\{[^{}]*(?:\.unnumbered|(?:^|[{\s])-(?=[\s}]))[^{}]*\}[\s#]*$/.test(line)) {
    return true;
  }
  const text = markdown ? setextHeadingText(lines, index, hidden) ?? atxHeadingText(line) : line.trim();
  return rules.sectionHeading.test(text ?? "");
}

// One chapter titled by the first `# ` heading outside code and comments,
// with any text before it kept, or by the file name. Stdin has no file
// name, so its chapter takes a number instead.
function singleChapter(text, document) {
  const lines = text.split("\n");
  const hidden = hiddenLineIndexes(lines);
  const index = lines.findIndex((line, lineIndex) => !hidden.has(lineIndex) && /^#[ \t]+\S/.test(line));
  if (index !== -1) {
    const before = lines.slice(0, index).join("\n").trim();
    const after = lines.slice(index + 1).join("\n").trim();
    return {
      title: atxHeadingText(lines[index]),
      prose: [before, after].filter((part) => part !== "").join("\n\n")
    };
  }

  // With no heading, the text may open with a plain title line.
  return {
    title: document.untitled ? "" : titleCaseSlug(path.basename(document.name, path.extname(document.name))),
    prose: text.trim(),
    titleLine: true
  };
}

// Drops the book title before the first chapter: a leading `# Title` or a
// setext title underlined with `===`. A part heading is prose and stays.
function stripTitleHeading(text, rules) {
  const lines = text.split("\n");
  const first = lines.findIndex((line) => line.trim() !== "");
  if (first === -1) {
    return text;
  }
  const atx = atxHeadingText(lines[first].trimStart());
  if (atx !== null && /^\s*#[ \t]/.test(lines[first])) {
    return rules.partHeading.test(atx) ? text : lines.slice(first + 1).join("\n");
  }
  if (setextHeadingText(lines, first, new Set(), /^ {0,3}=+[ \t]*$/) !== null) {
    return lines.slice(first + 2).join("\n");
  }
  return text;
}

function chapterMarkdown(title, number, counts, prose, unnumbered = false, authors = []) {
  return `${stringifyFrontmatter({
    title,
    number,
    ...(unnumbered ? { numbered: false } : {}),
    // One name as text, a story written together as a list.
    ...(authors.length === 0 ? {} : { author: authors.length === 1 ? authors[0] : authors }),
    pov: "",
    locations: [],
    characters: [],
    "arcs-advanced": [],
    status: "draft",
    ...counts
  })}# ${unnumbered ? title : chapterHeading(number, title)}

## Chapter Text

${prose}
`;
}
